const DB_KEYS=['proqtrack_db_v6','proqtrack_db_v7'];
const ROUTES=new Set(['#/reports','#/reports/attendance','#/reports/employees','#/reports/projects','#/reports/field','#/reports/supervisors','#/reports/audit']);
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(DB_KEYS[0])||localStorage.getItem(DB_KEYS[1])||'{}')}catch{return{}}};
const write=db=>{const s=JSON.stringify(db);DB_KEYS.forEach(k=>localStorage.setItem(k,s));window.dispatchEvent(new CustomEvent('proqtrack:db-updated'))};
const acct=()=>window.FT?.state?.account||{};
const role=()=>String(acct().role||'employee').toLowerCase();
const eid=()=>acct().employeeId||'';
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>today().slice(0,7)+'-01';
const pick=(o,keys,f='')=>keys.map(k=>o?.[k]).find(v=>v!==undefined&&v!==null&&v!=='')??f;
const rowDate=o=>String(pick(o,['date','attendanceDate','visitDate','checkInAt','createdAt','timestamp','updatedAt'],'')).slice(0,10);
const status=o=>String(pick(o,['status','attendanceStatus','visitStatus'],'-'));
const dateLabel=v=>v?new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'-';

function init(){const db=read();let dirty=false;for(const k of ['reportTemplates','reportJobs','reportExports','reportFilters','auditLogs'])if(!Array.isArray(db[k])){db[k]=[];dirty=true}if(!db.reportTemplates.length){db.reportTemplates=[{id:'RPT-ATT',name:'Rekap Absensi',type:'attendance',status:'active'},{id:'RPT-EMP',name:'Data Karyawan',type:'employees',status:'active'},{id:'RPT-PRJ',name:'Ringkasan Klien & Project',type:'projects',status:'active'},{id:'RPT-FLD',name:'Aktivitas Lapangan',type:'field',status:'active'}];dirty=true}if(dirty)write(db)}
function scope(db){if(['manager','admin'].includes(role()))return{employees:null,projects:null};const a=db.projectAssignments||[],me=eid();if(role()==='supervisor'){const projects=new Set(a.filter(x=>x.employeeId===me&&x.status==='active').map(x=>x.projectId));const employees=new Set([me]);a.filter(x=>projects.has(x.projectId)&&x.status==='active'&&(!x.supervisorId||x.supervisorId===me||x.employeeId===me)).forEach(x=>employees.add(x.employeeId));return{employees,projects}}return{employees:new Set([me]),projects:new Set(a.filter(x=>x.employeeId===me&&x.status==='active').map(x=>x.projectId))}}
function ctx(filters={}){const db=read(),s=scope(db);const employees=(db.employees||[]).filter(x=>!s.employees||s.employees.has(x.id));let projects=(db.projects||[]).filter(x=>!s.projects||s.projects.has(x.id));if(filters.clientId)projects=projects.filter(x=>x.clientId===filters.clientId);if(filters.projectId)projects=projects.filter(x=>x.id===filters.projectId);const eids=new Set(employees.map(x=>x.id)),pids=new Set(projects.map(x=>x.id));const ok=row=>{const re=pick(row,['employeeId','userId']),rp=pick(row,['projectId']),d=rowDate(row);return(!re||eids.has(re))&&(!rp||pids.has(rp))&&(!filters.employeeId||re===filters.employeeId)&&(!filters.projectId||rp===filters.projectId)&&(!filters.start||!d||d>=filters.start)&&(!filters.end||!d||d<=filters.end)};return{db,employees,projects,assignments:(db.projectAssignments||[]).filter(x=>(!s.employees||s.employees.has(x.employeeId))&&(!s.projects||s.projects.has(x.projectId))),attendance:(db.attendance||[]).filter(ok),visits:(db.visits||[]).filter(ok),photos:(db.fieldPhotos||db.photos||[]).filter(ok),leaves:(db.leaves||[]).filter(ok)}}
const emp=(c,id)=>c.employees.find(x=>x.id===id)?.name||id||'-';
const prj=(c,id)=>c.projects.find(x=>x.id===id)?.name||id||'-';
const cli=(c,id)=>c.db.clients?.find(x=>x.id===id)?.name||id||'-';
const options=(rows,label)=>'<option value="">Semua</option>'+rows.map(x=>`<option value="${esc(x.id)}">${esc(label(x))}</option>`).join('');
function table(headers,rows){return rows.length?`<div class="rpt-table-wrap"><table class="rpt-table"><thead><tr>${headers.map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<div class="rpt-empty">Tidak ada data sesuai cakupan dan filter.</div>'}
function tabs(){const t=[['#/reports','Ringkasan'],['#/reports/attendance','Kehadiran'],['#/reports/employees','Karyawan'],['#/reports/projects','Klien & Project'],['#/reports/field','Aktivitas Lapangan'],['#/reports/supervisors','Supervisor'],['#/reports/audit','Audit']];return`<nav class="rpt-nav" aria-label="Navigasi laporan">${t.map(([r,l])=>`<a href="${r}" class="${location.hash===r?'active':''}" ${location.hash===r?'aria-current="page"':''}>${l}</a>`).join('')}</nav>`}
function page(title,sub,body){return`<div class="rpt-wrap">${tabs()}<div class="rpt-page-title"><div><h3>${esc(title)}</h3><p>${esc(sub)}</p></div><a class="btn btn-secondary btn-sm" href="#/reports">Report Builder</a></div>${body}</div>`}
function field(id,label,control){return`<div><label class="label" for="${id}">${label}</label>${control}</div>`}
function builder(){const c=ctx();return`<div class="rpt-builder"><div class="rpt-page-title"><div><h3>Report Builder</h3><p>Segmentasikan data sebelum datasheet atau dokumen dibuat.</p></div><span class="rpt-badge">Fase 3</span></div><form id="rptFilterForm" class="rpt-filters" onsubmit="Reports.preview(event)">${field('rpt-type','Jenis Laporan','<select id="rpt-type" class="select" name="type"><option value="attendance">Kehadiran</option><option value="employees">Karyawan</option><option value="projects">Klien & Project</option><option value="field">Aktivitas Lapangan</option><option value="supervisors">Supervisor</option></select>')}${field('rpt-client','Klien',`<select id="rpt-client" class="select" name="clientId" onchange="Reports.syncProjects()">${options(c.db.clients||[],x=>x.name)}</select>`)}${field('rpt-project','Project',`<select id="rpt-project" class="select" name="projectId">${options(c.projects,x=>(x.code||'')+' — '+x.name)}</select>`)}${field('rpt-employee','Karyawan',`<select id="rpt-employee" class="select" name="employeeId">${options(c.employees,x=>x.name)}</select>`)}${field('rpt-start','Mulai',`<input id="rpt-start" class="input" type="date" name="start" value="${monthStart()}">`)}${field('rpt-end','Sampai',`<input id="rpt-end" class="input" type="date" name="end" value="${today()}">`)}${field('rpt-status','Status','<select id="rpt-status" class="select" name="status"><option value="">Semua</option><option>present</option><option>late</option><option>absent</option><option>leave</option><option>active</option><option>inactive</option></select>')}<div class="rpt-actions"><button class="btn btn-primary" type="submit">Tampilkan Preview</button><button class="btn btn-secondary" type="button" onclick="Reports.saveDraft()">Simpan Filter</button></div></form><div id="rptPreview" aria-live="polite"><div class="rpt-empty">Pilih filter lalu tampilkan preview.</div></div></div>`}
function overview(){const c=ctx({start:monthStart(),end:today()}),late=c.attendance.filter(x=>/late|terlambat/i.test(status(x))).length;return`<div class="rpt-wrap"><div class="rpt-hero"><div><h2>Pusat Laporan ProQTrack</h2><p>Segmentasi per klien, project, periode, supervisor, dan karyawan.</p></div><span class="rpt-badge">Fase 3</span></div>${tabs()}<div class="rpt-grid"><div class="rpt-card"><strong>${c.employees.length}</strong><span>Karyawan dalam cakupan</span></div><div class="rpt-card"><strong>${c.projects.filter(x=>x.status==='active').length}</strong><span>Project aktif</span></div><div class="rpt-card"><strong>${c.attendance.length}</strong><span>Record absensi bulan ini</span></div><div class="rpt-card"><strong>${late}</strong><span>Keterlambatan bulan ini</span></div></div>${builder()}</div>`}
function attendancePage(){const c=ctx({start:monthStart(),end:today()});return page('Laporan Kehadiran','Jam masuk, pulang, status, lokasi, dan project.',table(['Tanggal','Karyawan','Project','Status','Masuk','Pulang','Lokasi'],c.attendance.map(a=>[dateLabel(rowDate(a)),esc(emp(c,pick(a,['employeeId','userId']))),esc(prj(c,a.projectId)),`<span class="rpt-badge">${esc(status(a))}</span>`,esc(pick(a,['checkIn','checkInAt','timeIn'],'-')),esc(pick(a,['checkOut','checkOutAt','timeOut'],'-')),esc(pick(a,['area','locationName','location'],'-'))])))}
function employeesPage(){const c=ctx();return page('Laporan Karyawan','Profil, status, area, dan penempatan project.',table(['ID','Nama','Jabatan','Area','Status','Project Aktif'],c.employees.map(e=>[esc(e.id),esc(e.name),esc(pick(e,['role','jobRole'],'-')),esc(pick(e,['area','region'],'-')),`<span class="rpt-badge">${esc(e.status||'-')}</span>`,esc(c.assignments.filter(a=>a.employeeId===e.id&&a.status==='active').map(a=>prj(c,a.projectId)).join(', ')||'-')])))}
function projectsPage(){const c=ctx();return page('Laporan Klien & Project','Headcount, periode, status, dan aktivitas project.',table(['Kode','Project','Klien','Status','Mulai','Selesai','HC Aktif','Visit'],c.projects.map(p=>[esc(p.code||p.id),esc(p.name),esc(cli(c,p.clientId)),`<span class="rpt-badge">${esc(p.status||'-')}</span>`,dateLabel(p.startDate),dateLabel(p.endDate),String(c.assignments.filter(a=>a.projectId===p.id&&a.status==='active').length),String(c.visits.filter(v=>v.projectId===p.id).length)])))}
function fieldPage(){const c=ctx({start:monthStart(),end:today()}),rows=[...c.visits.map(v=>({kind:'Kunjungan',...v})),...c.photos.map(p=>({kind:'Foto',...p}))].sort((a,b)=>rowDate(b).localeCompare(rowDate(a))).map(x=>[dateLabel(rowDate(x)),esc(x.kind),esc(emp(c,pick(x,['employeeId','userId']))),esc(prj(c,x.projectId)),esc(pick(x,['outletName','title','category','photoType'],'-')),`<span class="rpt-badge">${esc(status(x))}</span>`]);return page('Laporan Aktivitas Lapangan','Kunjungan dan dokumentasi foto dalam satu timeline.',table(['Tanggal','Aktivitas','Karyawan','Project','Detail','Status'],rows))}
function supervisorsPage(){const c=ctx(),sup=c.employees.filter(e=>/supervisor/i.test(e.role||'')||c.assignments.some(a=>a.employeeId===e.id&&a.roleOnProject==='supervisor')),rows=sup.map(s=>{const team=new Set(c.assignments.filter(a=>a.supervisorId===s.id&&a.status==='active').map(a=>a.employeeId)),projects=new Set(c.assignments.filter(a=>(a.employeeId===s.id||a.supervisorId===s.id)&&a.status==='active').map(a=>a.projectId)),att=c.attendance.filter(a=>team.has(a.employeeId)),present=att.filter(a=>/present|hadir|late|terlambat/i.test(status(a))).length;return[esc(s.name),String(team.size),String(projects.size),String(att.length),att.length?Math.round(present/att.length*100)+'%':'-']});return page('Laporan Supervisor','Cakupan tim, project, dan tingkat kehadiran.',table(['Supervisor','Anggota','Project','Record Absensi','Kehadiran'],rows))}
function auditPage(){const db=read(),logs=(db.auditLogs||[]).slice().reverse();return page('Audit Log','Riwayat perubahan data dan aktivitas pengguna.',table(['Waktu','Pelaku','Aksi','Entitas','ID','Keterangan'],logs.map(l=>[dateLabel(l.createdAt),esc(l.actorName||l.actorId||'-'),esc(l.action||'-'),esc(l.entityType||'-'),esc(l.entityId||'-'),esc(l.description||'-')]))) }
function preview(type,f){const c=ctx(f),st=f.status;if(type==='attendance'){let r=c.attendance;if(st)r=r.filter(x=>status(x)===st);return table(['Tanggal','Karyawan','Project','Status'],r.map(a=>[dateLabel(rowDate(a)),esc(emp(c,pick(a,['employeeId','userId']))),esc(prj(c,a.projectId)),esc(status(a))]))}if(type==='employees'){let r=c.employees;if(st)r=r.filter(x=>x.status===st);return table(['ID','Nama','Role','Area','Status'],r.map(e=>[esc(e.id),esc(e.name),esc(e.role||'-'),esc(e.area||'-'),esc(e.status||'-')]))}if(type==='projects'){let r=c.projects;if(st)r=r.filter(x=>x.status===st);return table(['Kode','Project','Klien','Status'],r.map(p=>[esc(p.code||p.id),esc(p.name),esc(cli(c,p.clientId)),esc(p.status||'-')]))}if(type==='field')return table(['Tanggal','Jenis','Karyawan','Project'],[...c.visits.map(v=>[dateLabel(rowDate(v)),'Kunjungan',esc(emp(c,v.employeeId)),esc(prj(c,v.projectId))]),...c.photos.map(p=>[dateLabel(rowDate(p)),'Foto',esc(emp(c,p.employeeId)),esc(prj(c,p.projectId))])]);return supervisorsPage()}
window.Reports={preview(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target).entries());document.getElementById('rptPreview').innerHTML=preview(f.type,f)},syncProjects(){const f=document.getElementById('rptFilterForm');if(!f)return;const c=ctx(),client=f.clientId.value;f.projectId.innerHTML=options(c.projects.filter(p=>!client||p.clientId===client),x=>(x.code||'')+' — '+x.name)},saveDraft(){const f=document.getElementById('rptFilterForm');if(!f)return;const filters=Object.fromEntries(new FormData(f).entries()),db=read(),id='RPF-'+Date.now();db.reportFilters=db.reportFilters||[];db.reportFilters.push({id,name:filters.type+' '+filters.start+'–'+filters.end,filters,createdAt:new Date().toISOString(),createdBy:acct().id||null});db.auditLogs=db.auditLogs||[];db.auditLogs.push({id:'AUD-'+Date.now(),createdAt:new Date().toISOString(),actorId:acct().id,actorName:acct().email||acct().name,action:'create',entityType:'report_filter',entityId:id,description:'Menyimpan filter laporan'});write(db);window.showToast?.('Filter laporan disimpan','success')}};
function styles(){if(document.getElementById('reports-css'))return;const s=document.createElement('style');s.id='reports-css';s.textContent=`.rpt-wrap{display:grid;gap:16px}.rpt-hero{background:linear-gradient(135deg,#fff7ed,#fff);border:1px solid #fed7aa;border-radius:16px;padding:20px;display:flex;justify-content:space-between;gap:16px}.rpt-hero h2{font-size:22px;margin:0 0 5px}.rpt-hero p,.rpt-page-title p{color:var(--gray-500);font-size:12px;margin:0}.rpt-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.rpt-card,.rpt-builder{background:#fff;border:1px solid var(--gray-200);border-radius:14px;padding:16px}.rpt-card strong{display:block;font-size:24px}.rpt-card span{font-size:12px;color:var(--gray-500)}.rpt-filters{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:14px}.rpt-actions{display:flex;gap:8px;align-items:end}.rpt-table-wrap{overflow:auto;border:1px solid var(--gray-200);border-radius:12px}.rpt-table{width:100%;border-collapse:collapse;min-width:760px;background:#fff}.rpt-table th,.rpt-table td{padding:10px 12px;border-bottom:1px solid var(--gray-100);text-align:left;font-size:12px}.rpt-table th{background:var(--gray-50);color:var(--gray-600)}.rpt-nav{display:flex;gap:8px;flex-wrap:wrap}.rpt-nav a{padding:8px 11px;border:1px solid var(--gray-200);border-radius:8px;text-decoration:none;color:var(--gray-600);background:#fff;font-size:12px}.rpt-nav a.active{background:var(--brand-light);color:var(--brand-dark);border-color:#fed7aa}.rpt-empty{padding:36px;text-align:center;color:var(--gray-400)}.rpt-badge{display:inline-flex;padding:3px 8px;border-radius:999px;background:var(--gray-100);font-size:11px}.rpt-page-title{display:flex;justify-content:space-between;align-items:center;gap:12px}.rpt-page-title h3{font-size:18px;margin:0}#rptPreview{margin-top:16px}@media(max-width:1000px){.rpt-grid,.rpt-filters{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:640px){.rpt-grid,.rpt-filters{grid-template-columns:1fr}.rpt-hero{flex-direction:column}.rpt-actions{flex-direction:column;align-items:stretch}}`;document.head.appendChild(s)}
function nav(){if(!acct().role)return;const n=document.querySelector('.sidebar-nav');if(!n||n.querySelector('[data-reports-nav]'))return;const w=document.createElement('div');w.dataset.reportsNav='1';w.innerHTML='<div class="nav-section-label">Analitik</div><a class="nav-item" href="#/reports"><span class="nav-icon" aria-hidden="true">▧</span><span>Laporan</span></a>';n.appendChild(w)}
let renderedRoute='';
function render(force=false){if(!ROUTES.has(location.hash))return false;const root=document.querySelector('.content');if(!root)return false;if(!force&&renderedRoute===location.hash&&root.dataset.reportCore==='v2')return true;let html=overview();if(location.hash==='#/reports/attendance')html=attendancePage();else if(location.hash==='#/reports/employees')html=employeesPage();else if(location.hash==='#/reports/projects')html=projectsPage();else if(location.hash==='#/reports/field')html=fieldPage();else if(location.hash==='#/reports/supervisors')html=supervisorsPage();else if(location.hash==='#/reports/audit')html=auditPage();root.innerHTML=html;root.dataset.reportCore='v2';renderedRoute=location.hash;const t=document.querySelector('.topbar-title');if(t)t.textContent='Laporan';const st=document.querySelector('.topbar-subtitle');if(st){st.textContent='Analitik dan segmentasi data operasional';st.style.display='block'}return true}
function sync(force=false){styles();nav();render(force);document.querySelectorAll('[data-reports-nav] .nav-item').forEach(x=>x.classList.toggle('active',location.hash.startsWith('#/reports')))}
const shellObserver=new MutationObserver(()=>{if(!document.querySelector('.sidebar-nav')||!document.querySelector('.content'))return;sync(false)});
shellObserver.observe(document.documentElement,{childList:true,subtree:true});
window.addEventListener('hashchange',()=>{renderedRoute='';setTimeout(()=>sync(true))});
window.addEventListener('storage',()=>sync(true));
init();sync(true);export {};