import { getDB, persistDB } from '../lib/db.js';
const ROUTES=new Set(['#/reports','#/reports/attendance','#/reports/employees','#/reports/projects','#/reports/field','#/reports/supervisors','#/reports/stocks','#/reports/prices','#/reports/competitors','#/reports/custom','#/reports/audit']);
const TAB_LINKS=[['#/reports','Summary'],['#/reports/attendance','Attendance'],['#/reports/employees','Employees'],['#/reports/projects','Clients & Projects'],['#/reports/field','Field Activity'],['#/reports/stocks','Stock'],['#/reports/prices','Prices'],['#/reports/competitors','Competitors'],['#/reports/supervisors','Supervisor'],['#/reports/custom','Custom'],['#/reports/audit','Audit'],['#/reports/templates','Templates'],['#/reports/approvals','Approvals'],['#/reports/schedules','Scheduled']];
const SKIP_KEYS=new Set(['password','passwordHash','hash','dataUrl','photo','signatureImage','token','uploadToken','companyLogoFile']);
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const read=()=>getDB();
const write=db=>{
  const live=getDB();
  if(db&&db!==live)Object.assign(live,db);
  persistDB('reports');
};
const acct=()=>window.FT?.state?.account||{};
const role=()=>String(acct().role||'employee').toLowerCase();
const eid=()=>acct().employeeId||'';
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>today().slice(0,7)+'-01';
const pick=(o,keys,f='')=>keys.map(k=>o?.[k]).find(v=>v!==undefined&&v!==null&&v!=='')??f;
const rowDate=o=>String(pick(o,['date','attendanceDate','visitDate','checkInAt','createdAt','timestamp','updatedAt'],'')).slice(0,10);
const status=o=>String(pick(o,['status','attendanceStatus','visitStatus'],'-'));
const dateLabel=v=>v?new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'-';

function init(){const db=read();let dirty=false;for(const k of ['reportTemplates','reportJobs','reportExports','reportFilters','auditLogs'])if(!Array.isArray(db[k])){db[k]=[];dirty=true}const seed=[{id:'RPT-ATT',name:'Rekap Absensi',type:'attendance'},{id:'RPT-EMP',name:'Data Karyawan',type:'employees'},{id:'RPT-PRJ',name:'Ringkasan Klien & Project',type:'projects'},{id:'RPT-FLD',name:'Aktivitas Lapangan',type:'field'},{id:'RPT-STK',name:'Stok Outlet',type:'stocks'},{id:'RPT-PRC',name:'Harga & Diskon',type:'prices'},{id:'RPT-CMP',name:'Intel Kompetitor',type:'competitors'}];seed.forEach(t=>{if(!db.reportTemplates.some(x=>x.id===t.id||x.type===t.type)){db.reportTemplates.push({...t,status:'active'});dirty=true}});if(dirty)write(db)}
function scope(db){if(['superadmin','head','admin'].includes(role()))return{employees:null,projects:null};if(role()==='manager'){const pid=acct().projectId;return{employees:null,projects:pid?new Set([pid]):new Set()}}const a=db.projectAssignments||[],me=eid();if(role()==='supervisor'){const projects=new Set(a.filter(x=>x.employeeId===me&&x.status==='active').map(x=>x.projectId));const employees=new Set([me]);a.filter(x=>projects.has(x.projectId)&&x.status==='active'&&(!x.supervisorId||x.supervisorId===me||x.employeeId===me)).forEach(x=>employees.add(x.employeeId));return{employees,projects}}return{employees:new Set([me]),projects:new Set(a.filter(x=>x.employeeId===me&&x.status==='active').map(x=>x.projectId))}}
function ctx(filters={}){const db=read(),s=scope(db);const employees=(db.employees||[]).filter(x=>!s.employees||s.employees.has(x.id));let projects=(db.projects||[]).filter(x=>!s.projects||s.projects.has(x.id));if(filters.clientId)projects=projects.filter(x=>x.clientId===filters.clientId);if(filters.projectId)projects=projects.filter(x=>x.id===filters.projectId);const eids=new Set(employees.map(x=>x.id)),pids=new Set(projects.map(x=>x.id));const ok=row=>{const re=pick(row,['employeeId','userId']),rp=pick(row,['projectId']),d=rowDate(row);return(!re||eids.has(re))&&(!rp||pids.has(rp))&&(!filters.employeeId||re===filters.employeeId)&&(!filters.projectId||rp===filters.projectId)&&(!filters.start||!d||d>=filters.start)&&(!filters.end||!d||d<=filters.end)};return{db,employees,projects,assignments:(db.projectAssignments||[]).filter(x=>(!s.employees||s.employees.has(x.employeeId))&&(!s.projects||s.projects.has(x.projectId))),attendance:(db.attendance||[]).filter(ok),visits:(db.visits||[]).filter(ok),photos:(db.fieldPhotos||db.photos||[]).filter(ok),leaves:(db.leaves||[]).filter(ok),stocks:(db.stocks||[]).filter(ok),prices:(db.priceObservations||[]).filter(ok),intel:(db.competitorIntel||[]).filter(ok),competitors:db.competitors||[],outlets:db.outlets||[],products:db.products||[]}}
const emp=(c,id)=>c.employees.find(x=>x.id===id)?.name||id||'-';
const prj=(c,id)=>c.projects.find(x=>x.id===id)?.name||id||'-';
const cli=(c,id)=>c.db.clients?.find(x=>x.id===id)?.name||id||'-';
const options=(rows,label,sel='')=>'<option value="">Semua</option>'+rows.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(sel)?'selected':''}>${esc(label(x))}</option>`).join('');
function table(headers,rows){return rows.length?`<div class="rpt-table-wrap"><table class="rpt-table"><thead><tr>${headers.map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<div class="rpt-empty">Tidak ada data sesuai cakupan dan filter.</div>'}
function tabs(){return`<nav class="rpt-nav" aria-label="Navigasi laporan">${TAB_LINKS.map(([r,l])=>`<a href="${r}" class="${location.hash===r?'active':''}" ${location.hash===r?'aria-current="page"':''}>${l}</a>`).join('')}</nav>`}
function page(title,sub,body){return`<div class="rpt-wrap">${tabs()}<div class="rpt-page-title"><div><h3>${esc(title)}</h3><p>${esc(sub)}</p></div><a class="btn btn-secondary btn-sm" href="#/reports">Report Builder</a></div>${body}</div>`}
function field(id,label,control){return`<div><label class="label" for="${id}">${label}</label>${control}</div>`}
function builder(){const c=ctx();return`<div class="rpt-builder"><div class="rpt-page-title"><div><h3>Pembuat Laporan</h3><p>Segmentasikan data sebelum datasheet atau dokumen dibuat.</p></div></div><form id="rptFilterForm" class="rpt-filters" onsubmit="Reports.preview(event)">${field('rpt-type','Jenis Laporan','<select id="rpt-type" class="select" name="type"><option value="attendance">Kehadiran</option><option value="employees">Karyawan</option><option value="projects">Klien & Project</option><option value="field">Aktivitas Lapangan</option><option value="stocks">Stok</option><option value="prices">Harga</option><option value="competitors">Kompetitor</option><option value="supervisors">Supervisor</option><option value="custom">Custom</option></select>')}${field('rpt-client','Klien',`<select id="rpt-client" class="select" name="clientId" onchange="Reports.syncProjects()">${options(c.db.clients||[],x=>x.name)}</select>`)}${field('rpt-project','Project',`<select id="rpt-project" class="select" name="projectId">${options(c.projects,x=>(x.code||'')+' — '+x.name)}</select>`)}${field('rpt-employee','Karyawan',`<select id="rpt-employee" class="select" name="employeeId">${options(c.employees,x=>x.name)}</select>`)}${field('rpt-start','Mulai',`<input id="rpt-start" class="input" type="date" name="start" value="${monthStart()}">`)}${field('rpt-end','Sampai',`<input id="rpt-end" class="input" type="date" name="end" value="${today()}">`)}${field('rpt-status','Status','<select id="rpt-status" class="select" name="status"><option value="">Semua</option><option>present</option><option>late</option><option>absent</option><option>leave</option><option>active</option><option>inactive</option></select>')}<div class="rpt-actions"><button class="btn btn-primary" type="submit">Tampilkan Preview</button><button class="btn btn-secondary" type="button" onclick="Reports.saveDraft()">Simpan Filter</button></div></form><div id="rptPreview" aria-live="polite"><div class="rpt-empty">Pilih filter lalu tampilkan preview.</div></div></div>`}
function overview(){const c=ctx({start:monthStart(),end:today()}),late=c.attendance.filter(x=>/late|terlambat/i.test(status(x))).length;return`<div class="rpt-wrap">${tabs()}<div class="rpt-grid"><div class="rpt-card"><strong>${c.employees.length}</strong><span>Karyawan dalam cakupan</span></div><div class="rpt-card"><strong>${c.projects.filter(x=>x.status==='active').length}</strong><span>Project aktif</span></div><div class="rpt-card"><strong>${c.attendance.length}</strong><span>Record absensi bulan ini</span></div><div class="rpt-card"><strong>${late}</strong><span>Keterlambatan bulan ini</span></div></div>${builder()}</div>`}
function attendancePage(){const c=ctx({start:monthStart(),end:today()});return page('Laporan Kehadiran','Jam masuk, pulang, status, lokasi, dan project.',table(['Tanggal','Karyawan','Project','Status','Masuk','Pulang','Lokasi'],c.attendance.map(a=>[dateLabel(rowDate(a)),esc(emp(c,pick(a,['employeeId','userId']))),esc(prj(c,a.projectId)),`<span class="rpt-badge">${esc(status(a))}</span>`,esc(pick(a,['checkIn','checkInAt','timeIn'],'-')),esc(pick(a,['checkOut','checkOutAt','timeOut'],'-')),esc(pick(a,['area','locationName','location'],'-'))])))}
function employeesPage(){const c=ctx();return page('Laporan Karyawan','Profil, status, area, dan penempatan project.',table(['ID','Nama','Jabatan','Area','Status','Project Aktif'],c.employees.map(e=>[esc(e.id),esc(e.name),esc(pick(e,['role','jobRole'],'-')),esc(pick(e,['area','region'],'-')),`<span class="rpt-badge">${esc(e.status||'-')}</span>`,esc(c.assignments.filter(a=>a.employeeId===e.id&&a.status==='active').map(a=>prj(c,a.projectId)).join(', ')||'-')])))}
function projectsPage(){const c=ctx();return page('Laporan Klien & Project','Headcount, periode, status, dan aktivitas project.',table(['Kode','Project','Klien','Status','Mulai','Selesai','HC Aktif','Visit'],c.projects.map(p=>[esc(p.code||p.id),esc(p.name),esc(cli(c,p.clientId)),`<span class="rpt-badge">${esc(p.status||'-')}</span>`,dateLabel(p.startDate),dateLabel(p.endDate),String(c.assignments.filter(a=>a.projectId===p.id&&a.status==='active').length),String(c.visits.filter(v=>v.projectId===p.id).length)])))}
function fieldPage(){const c=ctx({start:monthStart(),end:today()}),rows=[...c.visits.map(v=>({kind:'Kunjungan',...v})),...c.photos.map(p=>({kind:'Foto',...p}))].sort((a,b)=>rowDate(b).localeCompare(rowDate(a))).map(x=>[dateLabel(rowDate(x)),esc(x.kind),esc(emp(c,pick(x,['employeeId','userId']))),esc(prj(c,x.projectId)),esc(pick(x,['outletName','title','category','photoType'],'-')),`<span class="rpt-badge">${esc(status(x))}</span>`]);return page('Laporan Aktivitas Lapangan','Kunjungan dan dokumentasi foto dalam satu timeline.',table(['Tanggal','Aktivitas','Karyawan','Project','Detail','Status'],rows))}
function supervisorsPage(){const c=ctx(),sup=c.employees.filter(e=>/supervisor/i.test(e.role||'')||c.assignments.some(a=>a.employeeId===e.id&&a.roleOnProject==='supervisor')),rows=sup.map(s=>{const team=new Set(c.assignments.filter(a=>a.supervisorId===s.id&&a.status==='active').map(a=>a.employeeId)),projects=new Set(c.assignments.filter(a=>(a.employeeId===s.id||a.supervisorId===s.id)&&a.status==='active').map(a=>a.projectId)),att=c.attendance.filter(a=>team.has(a.employeeId)),present=att.filter(a=>/present|hadir|late|terlambat/i.test(status(a))).length;return[esc(s.name),String(team.size),String(projects.size),String(att.length),att.length?Math.round(present/att.length*100)+'%':'-']});return page('Laporan Supervisor','Cakupan tim, project, dan tingkat kehadiran.',table(['Supervisor','Anggota','Project','Record Absensi','Kehadiran'],rows))}
function stocksPage(){const c=ctx();const prod=id=>c.products.find(x=>x.id===id)?.name||id||'-';const out=id=>c.outlets.find(x=>x.id===id)?.name||id||'-';return page('Laporan Stok','Qty, minimum, dan status stok di toko.',table(['Toko','Produk','Qty','Min','Status','Update'],c.stocks.map(s=>[esc(out(s.outletId)),esc(prod(s.productId)),String(s.quantity??'-'),String(s.minStock??'-'),`<span class="rpt-badge">${Number(s.quantity)<=Number(s.minStock)?'Menipis':'Aman'}</span>`,dateLabel(s.lastUpdated)])))}
function pricesPage(){const c=ctx();const prod=id=>c.products.find(x=>x.id===id)?.name||id||'-';const out=id=>c.outlets.find(x=>x.id===id)?.name||id||'-';return page('Laporan Harga','Observasi harga dan diskon dari kunjungan lapangan.',table(['Tanggal','Toko','Produk','Harga','Diskon %','Sales'],c.prices.map(p=>[dateLabel(p.recordedAt),esc(out(p.outletId)),esc(prod(p.productId)),esc(p.observedPrice??p.price??'-'),esc(p.discountPercent??0),esc(emp(c,p.recordedBy))])))}
function competitorsPage(){const c=ctx();const prod=id=>c.products.find(x=>x.id===id)?.name||id||'-';const out=id=>c.outlets.find(x=>x.id===id)?.name||id||'-';const brand=id=>(c.competitors.find(x=>x.id===id)||{}).name||id||'-';return page('Laporan Kompetitor','Intel harga, rak, dan promo kompetitor.',table(['Tanggal','Toko','Produk kita','Kompetitor','Harga kita','Harga komp','Shelf %','Promo'],c.intel.map(i=>[dateLabel(i.recordedAt),esc(out(i.outletId)),esc(prod(i.productId)),esc(brand(i.competitorId)),esc(i.ourPrice??'-'),esc(i.competitorPrice??'-'),esc(i.shelfShare??'-'),esc(i.hasPromo?'Ya':'Tidak')])))}
const TABLE_CATALOG=[
  ['employees','Karyawan',['id','employeeNumber','name','email','phone','role','jobRole','area','status','supervisorId','organizationId','joinDate']],
  ['accounts','Akun login',['id','email','name','role','employeeId','organizationId','status','mustChangePassword']],
  ['clients','Klien',['id','name','initials','status','industry','city']],
  ['projects','Project',['id','code','name','clientId','area','region','status','startDate','endDate','supervisorId','targetVisits','targetOutlets']],
  ['projectAssignments','Assignment project',['id','employeeId','projectId','roleOnProject','supervisorId','status','startDate','endDate']],
  ['outlets','Toko',['id','name','address','type','channel','area','city','owner','phone','status','lat','lng','clientId','organizationId']],
  ['outletProposals','Pengajuan toko',['id','name','address','area','status','submittedByName','submittedAt','supervisorStatus','managerStatus','projectId']],
  ['visits','Kunjungan',['id','employeeId','outletId','projectId','date','checkInTime','checkOutTime','status','notes','rating']],
  ['attendance','Absensi',['id','employeeId','date','checkInTime','checkOutTime','status','checkInLocation','locationType','projectId']],
  ['attendancePoints','Titik absensi',['id','name','type','address','outletId','organizationId']],
  ['leaves','Ijin & cuti',['id','employeeId','type','startDate','endDate','days','status','reason','submittedAt']],
  ['leaveTypes','Jenis cuti',['id','name','code','maxDays']],
  ['products','Products',['id','sku','name','brand','unit','price','status','category']],
  ['productSales','Product sales',['id','employeeId','productId','outletId','qty','unitPrice','amount','date','notes']],
  ['stocks','Stok',['id','outletId','productId','quantity','minStock','lastUpdated','projectId']],
  ['priceObservations','Harga & diskon',['id','outletId','productId','visitId','observedPrice','discountPercent','discountAmount','recordedBy','recordedAt','notes']],
  ['competitors','Merek kompetitor',['id','name','color','status']],
  ['competitorProducts','Produk kompetitor',['id','competitorId','name','sku','price']],
  ['competitorIntel','Intel kompetitor',['id','outletId','productId','competitorId','competitorProductId','ourPrice','competitorPrice','shelfShare','visibility','hasPromo','promoType','recordedBy','recordedAt']],
  ['fieldPhotos','Foto lapangan',['id','employeeId','outletId','visitId','projectId','photoType','caption','recordedAt']],
  ['activityEvidencePairs','Rack before/after',['id','visitId','outletId','employeeId','beforePhotoId','afterPhotoId','status','createdAt','completedAt']],
  ['surveyTemplates','Surveys',['id','name','description','projectId','status','startDate','endDate']],
  ['surveyAssignments','Survey assignment',['id','surveyId','projectId','supervisorId','employeeId','outletId']],
  ['surveyResponses','Survey responses',['id','surveyId','employeeId','outletId','visitId','status','submittedAt']],
  ['promoTypes','Tipe promo',['code','label','strategic']],
  ['organizations','Organisasi',['id','name','code','legalName','city','province','status','industry']],
  ['reportTemplates','Template laporan',['id','name','type','status','layout']],
  ['reportApprovals','Approval laporan',['id','documentNumber','title','status','requestedByName','requestedAt']],
  ['reportSchedules','Jadwal laporan',['id','name','reportType','frequency','time','status','nextRunAt']],
];
function listTables(db){const known=TABLE_CATALOG.map(([k,label])=>({key:k,label,count:Array.isArray(db[k])?db[k].length:0}));const extra=Object.keys(db).filter(k=>Array.isArray(db[k])&&typeof (db[k][0]||{})==='object'&&!TABLE_CATALOG.some(([x])=>x===k)&&!['reportJobs','reportExports','reportFilters','auditLogs'].includes(k)).map(k=>({key:k,label:k,count:db[k].length}));return [...known,...extra]}
function listColumns(db,table){const keys=new Set((TABLE_CATALOG.find(([k])=>k===table)||[,,[]])[2]||[]);(db[table]||[]).forEach(r=>Object.keys(r||{}).forEach(k=>{if(!SKIP_KEYS.has(k))keys.add(k)}));return [...keys]}
function colLabel(key){return key.replace(/([A-Z])/g,' $1').replace(/Id$/,' ID').replace(/^./,c=>c.toUpperCase())}
function cell(v){if(v==null||v==='')return'-';if(Array.isArray(v))return esc(v.join(', '));if(typeof v==='object')return esc(JSON.stringify(v).slice(0,80));return esc(v)}
function customState(){try{return JSON.parse(sessionStorage.getItem('rptCustom')||'{}')}catch{return{}}}
function saveCustomState(next){sessionStorage.setItem('rptCustom',JSON.stringify({...customState(),...next}))}
function projectIdsForClient(db,clientId){return new Set((db.projects||[]).filter(p=>!clientId||p.clientId===clientId).map(p=>p.id))}
function customRows(tableName,filters={}){const db=read();const s=scope(db);let rows=[...(db[tableName]||[])];const pids=projectIdsForClient(db,filters.clientId);if(s.employees)rows=rows.filter(r=>{const id=pick(r,['employeeId','userId','recordedBy','submittedBy']);return!id||s.employees.has(id)});if(s.projects)rows=rows.filter(r=>{const id=pick(r,['projectId']);const ids=r.projectIds;if(ids?.length)return ids.some(x=>s.projects.has(x));return!id||s.projects.has(id)});if(filters.clientId)rows=rows.filter(r=>{if(r.clientId)return r.clientId===filters.clientId;if(r.projectId)return pids.has(r.projectId);if(r.projectIds?.length)return r.projectIds.some(id=>pids.has(id));return true});if(filters.projectId)rows=rows.filter(r=>r.projectId===filters.projectId||r.projectIds?.includes(filters.projectId));if(filters.employeeId)rows=rows.filter(r=>[r.employeeId,r.userId,r.recordedBy,r.submittedBy].includes(filters.employeeId));if(filters.outletId)rows=rows.filter(r=>r.outletId===filters.outletId||r.id===filters.outletId);if(filters.area)rows=rows.filter(r=>String(r.area||r.region||'').toLowerCase()===String(filters.area).toLowerCase());if(filters.status)rows=rows.filter(r=>String(status(r)).toLowerCase()===String(filters.status).toLowerCase());if(filters.start)rows=rows.filter(r=>{const d=rowDate(r);return!d||d>=filters.start});if(filters.end)rows=rows.filter(r=>{const d=rowDate(r);return!d||d<=filters.end});if(filters.q){const q=String(filters.q).toLowerCase();rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q))}return rows}
function customPage(){const db=read();const tables=listTables(db);const st=customState();const table=tables.some(t=>t.key===st.table)?st.table:tables[0]?.key||'';const cols=listColumns(db,table);const picked=(st.cols||[]).filter(c=>cols.includes(c));const leftover=cols.filter(c=>!picked.includes(c));const c=ctx();const areas=[...new Set([...(db.employees||[]),...(db.outlets||[]),...(db.projects||[])].map(x=>x.area||x.region).filter(Boolean))];const statuses=[...new Set((db[table]||[]).map(r=>status(r)).filter(x=>x&&x!=='-'))];const filters=st.filters||{};const chips=picked.length?picked.map((k,i)=>`<span class="rpt-chip">${esc(colLabel(k))}<button type="button" onclick="Reports.customMoveCol(${i},-1)">↑</button><button type="button" onclick="Reports.customMoveCol(${i},1)">↓</button><button type="button" onclick="Reports.customDropCol('${esc(k)}')">✕</button></span>`).join(''):'<span class="am-muted">Belum ada kolom. Pilih dari dropdown Kolom.</span>';return page('Laporan Custom','Pilih tabel, lalu kolom, lalu saring datanya.',`<div class="rpt-builder"><form id="rptCustomForm" class="rpt-filters" onsubmit="Reports.customPreview(event)">
${field('rpt-c-table','1. Tabel',`<select id="rpt-c-table" class="select" name="table" onchange="Reports.customTable(this.value)">${tables.map(t=>`<option value="${esc(t.key)}" ${t.key===table?'selected':''}>${esc(t.label)} — ${t.key} (${t.count})</option>`).join('')}</select>`)}
${field('rpt-c-col','2. Tambah kolom',`<select id="rpt-c-col" class="select" onchange="if(this.value)Reports.customAddCol(this.value)"><option value="">Pilih kolom…</option>${leftover.map(k=>`<option value="${esc(k)}">${esc(colLabel(k))} (${k})</option>`).join('')}</select>`)}
${field('rpt-c-client','Klien',`<select id="rpt-c-client" class="select" name="clientId" onchange="Reports.customSyncProjects()">${options(db.clients||[],x=>x.name,filters.clientId)}</select>`)}
${field('rpt-c-project','Project',`<select id="rpt-c-project" class="select" name="projectId">${options((db.projects||[]).filter(p=>!filters.clientId||p.clientId===filters.clientId),x=>(x.code||'')+' — '+x.name,filters.projectId)}</select>`)}
${field('rpt-c-emp','Karyawan',`<select id="rpt-c-emp" class="select" name="employeeId">${options(c.employees,x=>x.name,filters.employeeId)}</select>`)}
${field('rpt-c-outlet','Toko',`<select id="rpt-c-outlet" class="select" name="outletId">${options(db.outlets||[],x=>x.name,filters.outletId)}</select>`)}
${field('rpt-c-start','Mulai',`<input id="rpt-c-start" class="input" type="date" name="start" value="${esc(filters.start||monthStart())}">`)}
${field('rpt-c-end','Sampai',`<input id="rpt-c-end" class="input" type="date" name="end" value="${esc(filters.end||today())}">`)}
${field('rpt-c-status','Status',`<select id="rpt-c-status" class="select" name="status"><option value="">Semua</option>${statuses.map(x=>`<option ${x===filters.status?'selected':''}>${esc(x)}</option>`).join('')}</select>`)}
${field('rpt-c-area','Area',`<select id="rpt-c-area" class="select" name="area"><option value="">Semua</option>${areas.map(a=>`<option ${a===filters.area?'selected':''}>${esc(a)}</option>`).join('')}</select>`)}
${field('rpt-c-q','Cari teks',`<input id="rpt-c-q" class="input" name="q" placeholder="Nama, kode, catatan…" value="${esc(filters.q||'')}">`)}
<div class="rpt-col-grid" id="rptSelectedCols">${chips}</div>
<div class="rpt-actions"><button class="btn btn-primary" type="submit">Tampilkan Preview</button><button class="btn btn-secondary" type="button" onclick="Reports.customSave()">Simpan template</button></div>
</form><div id="rptCustomPreview" style="margin-top:16px">${customTableHtml(table,picked,filters)}</div></div>`)}
function customTableHtml(tableName,cols,filters){const rows=customRows(tableName,filters||{});if(!cols.length)return'<div class="rpt-empty">Pilih kolom dari dropdown, lalu tampilkan preview.</div>';if(!rows.length)return'<div class="rpt-empty">Tidak ada data sesuai filter. Longgarkan klien, project, atau tanggal.</div>';const headers=cols.map(colLabel);return `<div class="rpt-empty" style="padding:10px;text-align:left">${rows.length} baris · ${cols.length} kolom · tabel ${esc(tableName)}</div>`+table(headers,rows.slice(0,500).map(r=>cols.map(k=>cell(r?.[k]))))}
function auditPage(){const db=read(),logs=(db.auditLogs||[]).slice().reverse();return page('Audit Log','Riwayat perubahan data dan aktivitas pengguna.',table(['Waktu','Pelaku','Aksi','Entitas','ID','Keterangan'],logs.map(l=>[dateLabel(l.createdAt),esc(l.actorName||l.actorId||'-'),esc(l.action||'-'),esc(l.entityType||'-'),esc(l.entityId||'-'),esc(l.description||'-')]))) }
function preview(type,f){const c=ctx(f),st=f.status;if(type==='attendance'){let r=c.attendance;if(st)r=r.filter(x=>status(x)===st);return table(['Tanggal','Karyawan','Project','Status'],r.map(a=>[dateLabel(rowDate(a)),esc(emp(c,pick(a,['employeeId','userId']))),esc(prj(c,a.projectId)),esc(status(a))]))}if(type==='employees'){let r=c.employees;if(st)r=r.filter(x=>x.status===st);return table(['ID','Nama','Role','Area','Status'],r.map(e=>[esc(e.id),esc(e.name),esc(e.role||'-'),esc(e.area||'-'),esc(e.status||'-')]))}if(type==='projects'){let r=c.projects;if(st)r=r.filter(x=>x.status===st);return table(['Kode','Project','Klien','Status'],r.map(p=>[esc(p.code||p.id),esc(p.name),esc(cli(c,p.clientId)),esc(p.status||'-')]))}if(type==='field')return table(['Tanggal','Jenis','Karyawan','Project'],[...c.visits.map(v=>[dateLabel(rowDate(v)),'Kunjungan',esc(emp(c,v.employeeId)),esc(prj(c,v.projectId))]),...c.photos.map(p=>[dateLabel(rowDate(p)),'Foto',esc(emp(c,p.employeeId)),esc(prj(c,p.projectId))])]);if(type==='stocks'){const prod=id=>c.products.find(x=>x.id===id)?.name||id||'-';const out=id=>c.outlets.find(x=>x.id===id)?.name||id||'-';return table(['Toko','Produk','Qty','Min'],c.stocks.map(s=>[esc(out(s.outletId)),esc(prod(s.productId)),String(s.quantity??'-'),String(s.minStock??'-')]))}if(type==='prices'){const prod=id=>c.products.find(x=>x.id===id)?.name||id||'-';const out=id=>c.outlets.find(x=>x.id===id)?.name||id||'-';return table(['Tanggal','Toko','Produk','Harga'],c.prices.map(p=>[dateLabel(p.recordedAt),esc(out(p.outletId)),esc(prod(p.productId)),esc(p.observedPrice??'-')]))}if(type==='competitors'){const prod=id=>c.products.find(x=>x.id===id)?.name||id||'-';return table(['Tanggal','Produk','Harga kita','Harga komp','Promo'],c.intel.map(i=>[dateLabel(i.recordedAt),esc(prod(i.productId)),esc(i.ourPrice??'-'),esc(i.competitorPrice??'-'),esc(i.hasPromo?'Ya':'Tidak')]))}if(type==='custom'){location.hash='#/reports/custom';return '<div class="rpt-empty">Membuka pembuat custom…</div>'}return supervisorsPage()}
window.Reports={preview(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target).entries());document.getElementById('rptPreview').innerHTML=preview(f.type,f)},syncProjects(){const f=document.getElementById('rptFilterForm');if(!f)return;const c=ctx(),client=f.clientId.value;f.projectId.innerHTML=options(c.projects.filter(p=>!client||p.clientId===client),x=>(x.code||'')+' — '+x.name)},saveDraft(){const f=document.getElementById('rptFilterForm');if(!f)return;const filters=Object.fromEntries(new FormData(f).entries()),db=read(),id='RPF-'+Date.now();db.reportFilters=db.reportFilters||[];db.reportFilters.push({id,name:filters.type+' '+filters.start+'–'+filters.end,filters,createdAt:new Date().toISOString(),createdBy:acct().id||null});db.auditLogs=db.auditLogs||[];db.auditLogs.push({id:'AUD-'+Date.now(),createdAt:new Date().toISOString(),actorId:acct().id,actorName:acct().email||acct().name,action:'create',entityType:'report_filter',entityId:id,description:'Menyimpan filter laporan'});write(db);window.showToast?.('Filter laporan disimpan','success')},customTable(name){saveCustomState({table:name,cols:[]});renderedRoute='';render(true)},customAddCol(key){const st=customState();const cols=[...(st.cols||[])];if(key&&!cols.includes(key))cols.push(key);saveCustomState({cols});renderedRoute='';render(true)},customDropCol(key){saveCustomState({cols:(customState().cols||[]).filter(x=>x!==key)});renderedRoute='';render(true)},customMoveCol(i,dir){const cols=[...(customState().cols||[])];const j=i+dir;if(j<0||j>=cols.length)return;[cols[i],cols[j]]=[cols[j],cols[i]];saveCustomState({cols});renderedRoute='';render(true)},customSyncProjects(){const form=document.getElementById('rptCustomForm');if(!form)return;const client=form.clientId.value;form.projectId.innerHTML=options(ctx().projects.filter(p=>!client||p.clientId===client),x=>(x.code||'')+' — '+x.name)},customPreview(e){e.preventDefault();const form=e.target;const table=form.table.value;const cols=customState().cols||[];const filters=Object.fromEntries(new FormData(form).entries());saveCustomState({table,cols,filters});const box=document.getElementById('rptCustomPreview');if(box)box.innerHTML=customTableHtml(table,cols,filters)},customSave(){const form=document.getElementById('rptCustomForm');if(!form)return;const table=form.table.value;const cols=customState().cols||[];if(!cols.length){window.showToast?.('Pilih kolom dulu','error');return}const filters=Object.fromEntries(new FormData(form).entries());const name=prompt('Nama template custom',`Custom ${table}`);if(!name)return;const db=read();db.reportTemplates=db.reportTemplates||[];db.reportTemplates.push({id:'TPL-'+Date.now(),name,type:'custom',table,columns:cols,filters,status:'active',createdAt:new Date().toISOString()});write(db);window.showToast?.('Template custom disimpan','success')}};
function styles(){if(document.getElementById('reports-css'))return;const s=document.createElement('style');s.id='reports-css';s.textContent=`.rpt-wrap{display:grid;gap:16px}.rpt-hero{background:linear-gradient(135deg,#fff7ed,#fff);border:1px solid #fed7aa;border-radius:16px;padding:20px;display:flex;justify-content:space-between;gap:16px}.rpt-hero h2{font-size:22px;margin:0 0 5px}.rpt-hero p,.rpt-page-title p{color:var(--gray-500);font-size:12px;margin:0}.rpt-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.rpt-card,.rpt-builder{background:#fff;border:1px solid var(--gray-200);border-radius:14px;padding:16px}.rpt-card strong{display:block;font-size:24px}.rpt-card span{font-size:12px;color:var(--gray-500)}.rpt-filters{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:14px}.rpt-actions{display:flex;gap:8px;align-items:end}.rpt-table-wrap{overflow:auto;border:1px solid var(--gray-200);border-radius:12px}.rpt-table{width:100%;border-collapse:collapse;min-width:760px;background:#fff}.rpt-table th,.rpt-table td{padding:10px 12px;border-bottom:1px solid var(--gray-100);text-align:left;font-size:12px}.rpt-table th{background:var(--gray-50);color:var(--gray-600)}.rpt-nav{display:flex;gap:8px;flex-wrap:wrap}.rpt-nav a{padding:8px 11px;border:1px solid var(--gray-200);border-radius:8px;text-decoration:none;color:var(--gray-600);background:#fff;font-size:12px}.rpt-nav a.active{background:var(--brand-light);color:var(--brand-dark);border-color:#fed7aa}.rpt-empty{padding:36px;text-align:center;color:var(--gray-400)}.rpt-badge{display:inline-flex;padding:3px 8px;border-radius:999px;background:var(--gray-100);font-size:11px}.rpt-col-grid{grid-column:1/-1;display:flex;flex-wrap:wrap;gap:8px;margin-top:4px}.rpt-col{display:inline-flex;align-items:center;gap:6px;padding:6px 10px;border:1px solid var(--gray-200);border-radius:8px;background:#fff;font-size:12px}.rpt-chip{display:inline-flex;align-items:center;gap:6px;padding:6px 8px;border-radius:999px;background:var(--brand-light);border:1px solid #fed7aa;font-size:12px}.rpt-chip button{border:0;background:transparent;cursor:pointer;color:var(--gray-500);font-size:11px;padding:0 2px}.rpt-page-title{display:flex;justify-content:space-between;align-items:center;gap:12px}.rpt-page-title h3{font-size:18px;margin:0}#rptPreview{margin-top:16px}@media(max-width:1000px){.rpt-grid,.rpt-filters{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:640px){.rpt-grid,.rpt-filters{grid-template-columns:1fr}.rpt-hero{flex-direction:column}.rpt-actions{flex-direction:column;align-items:stretch}}`;document.head.appendChild(s)}
function canSeeReports(){return ['superadmin','head','manager','admin'].includes(role())}
function nav(){const n=document.querySelector('.sidebar-nav');if(!n)return;const existing=n.querySelector('[data-reports-nav]');if(n.querySelector('a[href="#/reports"]')){existing?.remove();return}if(!canSeeReports()){existing?.remove();return}if(existing)return;const w=document.createElement('div');w.dataset.reportsNav='1';w.innerHTML='<div class="nav-section-label">Analitik</div><a class="nav-item" href="#/reports"><span class="nav-icon" aria-hidden="true">▧</span><span>Laporan</span></a>';n.appendChild(w)}
let renderedRoute='';
function render(force=false){if(!canSeeReports()||!ROUTES.has(location.hash))return false;const root=document.querySelector('.content');if(!root)return false;if(!force&&renderedRoute===location.hash&&root.dataset.reportCore==='v2')return true;let html=overview();if(location.hash==='#/reports/attendance')html=attendancePage();else if(location.hash==='#/reports/employees')html=employeesPage();else if(location.hash==='#/reports/projects')html=projectsPage();else if(location.hash==='#/reports/field')html=fieldPage();else if(location.hash==='#/reports/stocks')html=stocksPage();else if(location.hash==='#/reports/prices')html=pricesPage();else if(location.hash==='#/reports/competitors')html=competitorsPage();else if(location.hash==='#/reports/custom')html=customPage();else if(location.hash==='#/reports/supervisors')html=supervisorsPage();else if(location.hash==='#/reports/audit')html=auditPage();root.innerHTML=html;root.dataset.reportCore='v2';renderedRoute=location.hash;const t=document.querySelector('.topbar-title');if(t)t.textContent='Reports';const st=document.querySelector('.topbar-subtitle');if(st){st.textContent='Operational analytics and custom extracts';st.style.display='block'}return true}
function sync(force=false){styles();nav();render(force);document.querySelectorAll('[data-reports-nav] .nav-item').forEach(x=>x.classList.toggle('active',location.hash.startsWith('#/reports')))}
const shellObserver=new MutationObserver(()=>{if(!document.querySelector('.sidebar-nav')||!document.querySelector('.content'))return;sync(false)});
shellObserver.observe(document.documentElement,{childList:true,subtree:true});
window.addEventListener('hashchange',()=>{renderedRoute='';setTimeout(()=>sync(true))});
window.addEventListener('storage',()=>sync(true));
init();sync(true);export {};