const DB_KEYS=['proqtrack_db_v6','proqtrack_db_v7'];
const read=()=>{try{return JSON.parse(localStorage.getItem(DB_KEYS[0])||localStorage.getItem(DB_KEYS[1])||'{}')}catch{return{}}};
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const pick=(o,keys,f='')=>keys.map(k=>o?.[k]).find(v=>v!==undefined&&v!==null&&v!=='')??f;
const dateOf=o=>String(pick(o,['date','attendanceDate','visitDate','checkInAt','createdAt','timestamp','updatedAt'],'')).slice(0,10);
const statusOf=o=>String(pick(o,['status','attendanceStatus','visitStatus'],'-'));
const dateLabel=v=>v?new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'-';
const account=()=>window.FT?.state?.account||{};

function filters(){const form=document.getElementById('rptFilterForm');return form?Object.fromEntries(new FormData(form).entries()):{type:'attendance'};}
function documentNumber(db){const s=db.reportSettings||{};return `${s.documentPrefix||'PQT/RPT'}/${String(s.nextNumber||1).padStart(5,'0')}/${new Date().getFullYear()}`;}
function scopedRows(db,f,type){
  const employees=db.employees||[],projects=db.projects||[],clients=db.clients||[];
  const employeeName=id=>employees.find(x=>x.id===id)?.name||id||'-';
  const projectName=id=>projects.find(x=>x.id===id)?.name||id||'-';
  const clientName=id=>clients.find(x=>x.id===id)?.name||id||'-';
  const allowed=r=>{const d=dateOf(r),eid=pick(r,['employeeId','userId']),pid=r.projectId;return(!f.start||!d||d>=f.start)&&(!f.end||!d||d<=f.end)&&(!f.employeeId||eid===f.employeeId)&&(!f.projectId||pid===f.projectId)&&(!f.status||statusOf(r)===f.status)};
  if(type==='employees'||type==='individual'){
    const list=employees.filter(e=>!f.employeeId||e.id===f.employeeId).filter(e=>!f.status||e.status===f.status);
    return {headers:['ID','Nama','Jabatan','Area','Status'],rows:list.map(e=>[e.id,e.name,pick(e,['role','jobRole'],'-'),pick(e,['area','region'],'-'),e.status||'-'])};
  }
  if(type==='projects'){
    const list=projects.filter(p=>!f.clientId||p.clientId===f.clientId).filter(p=>!f.projectId||p.id===f.projectId).filter(p=>!f.status||p.status===f.status);
    return {headers:['Kode','Project','Klien','Status','Mulai','Selesai'],rows:list.map(p=>[p.code||p.id,p.name,clientName(p.clientId),p.status||'-',dateLabel(p.startDate),dateLabel(p.endDate)])};
  }
  if(type==='field'){
    const visits=(db.visits||[]).filter(allowed).map(r=>[dateLabel(dateOf(r)),'Kunjungan',employeeName(pick(r,['employeeId','userId'])),projectName(r.projectId),pick(r,['outletName','title','notes'],'-'),statusOf(r)]);
    const photos=(db.fieldPhotos||db.photos||[]).filter(allowed).map(r=>[dateLabel(dateOf(r)),'Foto',employeeName(pick(r,['employeeId','userId'])),projectName(r.projectId),pick(r,['title','category','photoType'],'-'),statusOf(r)]);
    return {headers:['Tanggal','Aktivitas','Karyawan','Project','Detail','Status'],rows:[...visits,...photos]};
  }
  const attendance=(db.attendance||[]).filter(allowed);
  return {headers:['Tanggal','Karyawan','Project','Status','Masuk','Pulang','Lokasi'],rows:attendance.map(r=>[dateLabel(dateOf(r)),employeeName(pick(r,['employeeId','userId'])),projectName(r.projectId),statusOf(r),pick(r,['checkIn','checkInAt','timeIn'],'-'),pick(r,['checkOut','checkOutAt','timeOut'],'-'),pick(r,['area','locationName','location'],'-')])};
}
function selectedTemplate(db,templateId,type){return db.reportTemplates?.find(t=>t.id===templateId)||db.reportTemplates?.find(t=>t.type===type)||{name:'Laporan ProQTrack',layout:'portrait',includeCompanyLogo:true,includeClientLogo:false,requireApproval:false};}
function clientLogo(db,f){const c=(db.clients||[]).find(x=>x.id===f.clientId);return pick(c,['logo','logoUrl','clientLogo'],'');}
function previewHtml(templateId){
  const db=read(),f=filters(),type=templateId?db.reportTemplates?.find(t=>t.id===templateId)?.type||f.type:f.type||'attendance';
  const t=selectedTemplate(db,templateId,type),s=db.reportSettings||{},data=scopedRows(db,f,type);
  const companyLogo=t.includeCompanyLogo&&s.companyLogo?`<img src="${esc(s.companyLogo)}" alt="Logo ${esc(s.companyName||'perusahaan')}">`:'';
  const cLogo=t.includeClientLogo&&clientLogo(db,f)?`<img src="${esc(clientLogo(db,f))}" alt="Logo klien">`:'';
  const rows=data.rows.slice(0,250);
  return `<article class="r4-paper ${t.layout==='landscape'?'landscape':''}"><div class="r4-watermark">DRAFT PREVIEW</div><header><div class="r4-brand">${companyLogo}<div><strong>${esc(s.companyName||'ProQTrack')}</strong><span>Dokumen Laporan Operasional</span></div></div><div class="r4-client-logo">${cLogo}</div></header><section class="r4-meta"><div><h1>${esc(t.name||'Laporan')}</h1><p>Preview sebelum generate dan approval final.</p></div><dl><div><dt>Nomor</dt><dd>${esc(documentNumber(db))}</dd></div><div><dt>Status</dt><dd>DRAFT</dd></div><div><dt>Dibuat</dt><dd>${esc(new Date().toLocaleString('id-ID'))}</dd></div><div><dt>Periode</dt><dd>${esc(f.start||'-')} s.d. ${esc(f.end||'-')}</dd></div></dl></section><div class="r4-table-wrap"><table><thead><tr>${data.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>${!rows.length?'<div class="r4-no-data">Tidak ada data sesuai filter.</div>':''}${data.rows.length>250?`<p class="r4-note">Preview dibatasi 250 dari ${data.rows.length} baris. File final tetap memuat seluruh data.</p>`:''}</div><footer><div><span>Disiapkan oleh</span><strong>${esc(account().name||account().email||'-')}</strong></div><div class="r4-sign"><span>Disetujui oleh</span>${s.signatureImage?`<img src="${esc(s.signatureImage)}" alt="Tanda tangan">`:'<div class="r4-sign-space"></div>'}<strong>${esc(s.signatureName||'Nama Approver')}</strong><small>${esc(s.signatureTitle||'Jabatan')}</small></div></footer></article>`;
}
function ensureModal(){
  let modal=document.getElementById('r4-preview-modal');if(modal)return modal;
  modal=document.createElement('div');modal.id='r4-preview-modal';modal.className='r4-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="r4-backdrop" data-r4-close></div><section class="r4-dialog" role="dialog" aria-modal="true" aria-labelledby="r4-preview-title"><div class="r4-toolbar"><div><strong id="r4-preview-title">Preview Dokumen</strong><span>Periksa branding, nomor, isi, dan tanda tangan sebelum generate.</span></div><div><button class="btn btn-secondary btn-sm" type="button" onclick="ReportPhase4Preview.print()">Print Preview</button><button class="btn btn-primary btn-sm" type="button" data-r4-close>Tutup</button></div></div><div id="r4-preview-content" class="r4-canvas"></div></section>`;document.body.appendChild(modal);modal.querySelectorAll('[data-r4-close]').forEach(el=>el.addEventListener('click',close));return modal;
}
function open(templateId=''){const modal=ensureModal();modal.querySelector('#r4-preview-content').innerHTML=previewHtml(templateId);modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';modal.querySelector('[data-r4-close]')?.focus();}
function close(){const modal=document.getElementById('r4-preview-modal');if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';}
function printPreview(){const content=document.querySelector('#r4-preview-content .r4-paper');if(!content)return;const w=window.open('','_blank');if(!w){window.showToast?.('Popup diblokir browser','error');return;}w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Preview Laporan</title><style>${document.getElementById('r4-preview-style')?.textContent||''}body{background:#fff!important;padding:0}.r4-paper{box-shadow:none;margin:0 auto}.r4-watermark{display:none}</style></head><body>${content.outerHTML}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300);}
function inject(){
  document.querySelectorAll('.rpt-export-actions').forEach(actions=>{if(actions.querySelector('[data-r4-preview]'))return;actions.insertAdjacentHTML('afterbegin','<button class="btn btn-secondary btn-sm" type="button" data-r4-preview onclick="ReportPhase4Preview.open()">Preview Dokumen</button>')});
  if(location.hash==='#/reports/templates')document.querySelectorAll('.rpt-table tbody tr').forEach((tr,i)=>{const cell=tr.lastElementChild;if(!cell||cell.querySelector('[data-r4-template-preview]'))return;const id=read().reportTemplates?.[i]?.id;if(id)cell.insertAdjacentHTML('afterbegin',`<button class="btn btn-secondary btn-sm" type="button" data-r4-template-preview onclick="ReportPhase4Preview.open('${esc(id)}')">Preview</button> `)});
}
function styles(){if(document.getElementById('r4-preview-style'))return;const s=document.createElement('style');s.id='r4-preview-style';s.textContent=`.r4-modal{position:fixed;inset:0;z-index:10000;display:none}.r4-modal.open{display:block}.r4-backdrop{position:absolute;inset:0;background:rgba(15,23,42,.72)}.r4-dialog{position:absolute;inset:20px;background:#eef2f7;border-radius:16px;display:flex;flex-direction:column;overflow:hidden}.r4-toolbar{background:#fff;border-bottom:1px solid #dbe2ea;padding:12px 16px;display:flex;align-items:center;justify-content:space-between;gap:16px}.r4-toolbar strong,.r4-toolbar span{display:block}.r4-toolbar span{font-size:11px;color:#64748b}.r4-toolbar>div:last-child{display:flex;gap:8px}.r4-canvas{overflow:auto;padding:24px}.r4-paper{position:relative;width:210mm;min-height:297mm;margin:auto;background:#fff;padding:16mm;box-shadow:0 18px 45px rgba(15,23,42,.18);color:#172033;font-family:Arial,sans-serif}.r4-paper.landscape{width:297mm;min-height:210mm}.r4-watermark{position:absolute;inset:45% auto auto 16%;font-size:52px;font-weight:800;color:rgba(220,38,38,.08);transform:rotate(-24deg);letter-spacing:8px;pointer-events:none}.r4-paper header{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #172033;padding-bottom:10px}.r4-brand{display:flex;align-items:center;gap:12px}.r4-brand img,.r4-client-logo img{max-width:120px;max-height:45px;object-fit:contain}.r4-brand strong,.r4-brand span{display:block}.r4-brand span{font-size:10px;color:#64748b}.r4-meta{display:flex;justify-content:space-between;gap:24px;margin:20px 0}.r4-meta h1{font-size:22px;margin:0 0 4px}.r4-meta p{font-size:11px;color:#64748b;margin:0}.r4-meta dl{margin:0;min-width:280px}.r4-meta dl>div{display:grid;grid-template-columns:85px 1fr;font-size:10px;padding:3px 0}.r4-meta dt{color:#64748b}.r4-meta dd{margin:0;font-weight:600}.r4-table-wrap{border:1px solid #cbd5e1}.r4-table-wrap table{width:100%;border-collapse:collapse;font-size:9px}.r4-table-wrap th,.r4-table-wrap td{border-bottom:1px solid #e2e8f0;border-right:1px solid #e2e8f0;padding:6px;text-align:left}.r4-table-wrap th{background:#f1f5f9;font-weight:700}.r4-no-data{padding:50px;text-align:center;color:#94a3b8}.r4-note{padding:8px;font-size:9px;color:#64748b}.r4-paper footer{display:grid;grid-template-columns:1fr 1fr;gap:80px;margin-top:35px;font-size:10px}.r4-paper footer span,.r4-paper footer strong,.r4-paper footer small{display:block}.r4-paper footer span{color:#64748b;margin-bottom:8px}.r4-sign{text-align:center}.r4-sign img{height:55px;max-width:150px;object-fit:contain}.r4-sign-space{height:55px}.r4-sign small{color:#64748b}@media(max-width:900px){.r4-dialog{inset:8px}.r4-toolbar{align-items:flex-start;flex-direction:column}.r4-canvas{padding:12px}.r4-paper{transform-origin:top left;zoom:.58}}@media print{.r4-modal,.r4-toolbar,.r4-backdrop{display:none}.r4-paper{box-shadow:none}}`;document.head.appendChild(s)}
window.ReportPhase4Preview={open,close,print:printPreview};
let queued=false;function sync(){queued=false;styles();inject()}new MutationObserver(()=>{if(!queued){queued=true;requestAnimationFrame(sync)}}).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(sync));styles();inject();export {};
