const DB_KEYS=['proqtrack_db_v6','proqtrack_db_v7'];
const ROUTES=new Set(['#/reports/templates','#/reports/approvals','#/reports/schedules','#/reports/archive']);
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(DB_KEYS[0])||localStorage.getItem(DB_KEYS[1])||'{}')}catch{return{}}};
const write=db=>{const text=JSON.stringify(db);DB_KEYS.forEach(k=>localStorage.setItem(k,text));window.dispatchEvent(new CustomEvent('proqtrack:db-updated'))};
const account=()=>window.FT?.state?.account||{};
const manager=()=>['manager','admin'].includes(String(account().role||'').toLowerCase());
const now=()=>new Date().toISOString();
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;
const fmt=v=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'-';
function init(){const db=read();let changed=false;for(const k of ['reportTemplates','reportApprovals','reportSchedules','reportExports','reportJobs','auditLogs'])if(!Array.isArray(db[k])){db[k]=[];changed=true}if(!db.reportSettings){db.reportSettings={companyName:'ProQTrack',companyLogo:'./assets/logo-light.svg',documentPrefix:'PQT/RPT',nextNumber:1,signatureName:'',signatureTitle:'',signatureImage:'',updatedAt:now()};changed=true}if(changed)write(db)}
function audit(db,action,entityType,entityId,description){db.auditLogs.push({id:uid('AUD'),createdAt:now(),actorId:account().id||null,actorName:account().email||account().name||'-',action,entityType,entityId,description})}
function number(db){const s=db.reportSettings||{};return `${s.documentPrefix||'PQT/RPT'}/${String(s.nextNumber||1).padStart(5,'0')}/${new Date().getFullYear()}`}
function tabs(){const links=[['#/reports','Ringkasan'],['#/reports/attendance','Kehadiran'],['#/reports/employees','Karyawan'],['#/reports/projects','Klien & Project'],['#/reports/field','Aktivitas Lapangan'],['#/reports/supervisors','Supervisor'],['#/reports/audit','Audit'],['#/reports/templates','Template'],['#/reports/approvals','Approval'],['#/reports/schedules','Terjadwal'],['#/reports/exports','Riwayat Ekspor'],['#/reports/archive','Arsip R2']];return `<nav class="rpt-nav" aria-label="Navigasi laporan">${links.map(([r,l])=>`<a href="${r}" class="${location.hash===r?'active':''}">${l}</a>`).join('')}</nav>`}
function table(headers,rows){return rows.length?`<div class="rpt-table-wrap"><table class="rpt-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<div class="rpt-empty">Belum ada data.</div>'}
function page(title,subtitle,body){return `<div class="rpt-wrap">${tabs()}<div class="rpt-page-title"><div><h3>${esc(title)}</h3><p>${esc(subtitle)}</p></div><span class="rpt-badge">Fase 4</span></div>${body}</div>`}
function templatesPage(){const db=read(),s=db.reportSettings||{};const form=`<div class="rpt-builder"><form class="rpt-filters" onsubmit="ReportPhase4.saveSettings(event)"><div><label class="label">Nama perusahaan</label><input class="input" name="companyName" value="${esc(s.companyName)}"></div><div><label class="label">URL/logo perusahaan</label><input class="input" name="companyLogo" value="${esc(s.companyLogo)}"></div><div><label class="label">Prefix nomor dokumen</label><input class="input" name="documentPrefix" value="${esc(s.documentPrefix)}"></div><div><label class="label">Nomor berikutnya</label><input class="input" type="number" min="1" name="nextNumber" value="${Number(s.nextNumber||1)}"></div><div><label class="label">Nama penandatangan</label><input class="input" name="signatureName" value="${esc(s.signatureName)}"></div><div><label class="label">Jabatan</label><input class="input" name="signatureTitle" value="${esc(s.signatureTitle)}"></div><div class="rpt-actions"><button class="btn btn-primary" ${manager()?'':'disabled'}>Simpan Identitas</button></div></form><div class="rpt-warning">Nomor dokumen berikutnya: <strong>${esc(number(db))}</strong></div></div>`;const rows=(db.reportTemplates||[]).map(t=>[esc(t.name),esc(t.type),esc(t.layout||'-'),t.includeCompanyLogo?'Ya':'Tidak',t.includeClientLogo?'Ya':'Tidak',t.requireApproval?'Ya':'Tidak',`<span class="rpt-badge">${esc(t.status)}</span>`,`<button class="btn btn-secondary btn-sm" onclick="ReportPhase4.editTemplate('${esc(t.id)}')" ${manager()?'':'disabled'}>Edit</button>`]);return page('Template Dokumen','Atur branding, kolom, layout, logo klien, dan approval.',form+`<div class="rpt-page-title"><div><h3>Daftar Template</h3><p>Konfigurasi template tanpa mengubah kode.</p></div><button class="btn btn-primary btn-sm" onclick="ReportPhase4.newTemplate()" ${manager()?'':'disabled'}>Tambah Template</button></div>`+table(['Nama','Jenis','Layout','Logo Perusahaan','Logo Klien','Approval','Status','Aksi'],rows))}
function approvalsPage(){const db=read();const rows=(db.reportApprovals||[]).slice().reverse().map(a=>[esc(a.documentNumber),esc(a.title),esc(a.requestedByName||'-'),fmt(a.requestedAt),`<span class="rpt-badge">${esc(a.status)}</span>`,esc(a.approvedByName||'-'),manager()&&a.status==='pending'?`<button class="btn btn-primary btn-sm" onclick="ReportPhase4.approve('${a.id}')">Setujui</button> <button class="btn btn-danger btn-sm" onclick="ReportPhase4.reject('${a.id}')">Tolak</button>`:'-']);return page('Approval Laporan','Persetujuan dokumen sebelum dinyatakan final.',`<div class="rpt-page-title"><div><h3>Permintaan Approval</h3></div><button class="btn btn-secondary btn-sm" onclick="ReportPhase4.requestApproval()">Buat Permintaan</button></div>${table(['Nomor','Dokumen','Pemohon','Waktu','Status','Approver','Aksi'],rows)}`)}
function schedulesPage(){const db=read();const rows=(db.reportSchedules||[]).map(s=>[esc(s.name),esc(s.reportType),esc(s.frequency),esc(s.time||'-'),fmt(s.nextRunAt),`<span class="rpt-badge">${esc(s.status)}</span>`,`<button class="btn btn-secondary btn-sm" onclick="ReportPhase4.toggleSchedule('${s.id}')" ${manager()?'':'disabled'}>${s.status==='active'?'Jeda':'Aktifkan'}</button>`]);const form=`<div class="rpt-builder"><form class="rpt-filters" onsubmit="ReportPhase4.saveSchedule(event)"><div><label class="label">Nama jadwal</label><input class="input" name="name" required></div><div><label class="label">Jenis laporan</label><select class="select" name="reportType"><option value="attendance">Kehadiran</option><option value="projects">Klien & Project</option><option value="field">Aktivitas Lapangan</option></select></div><div><label class="label">Frekuensi</label><select class="select" name="frequency"><option value="daily">Harian</option><option value="weekly">Mingguan</option><option value="monthly">Bulanan</option></select></div><div><label class="label">Jam</label><input class="input" type="time" name="time" value="08:00"></div><div><label class="label">Format</label><select class="select" name="format"><option>pdf</option><option>xlsx</option><option>docx</option><option>zip</option></select></div><div class="rpt-actions"><button class="btn btn-primary" ${manager()?'':'disabled'}>Simpan Jadwal</button></div></form></div>`;return page('Laporan Terjadwal','Kelola jadwal pembuatan laporan berulang.',form+table(['Nama','Jenis','Frekuensi','Jam','Jadwal Berikutnya','Status','Aksi'],rows))}
function archivePage(){const db=read();const rows=(db.reportExports||[]).filter(x=>x.r2Key||x.storageStatus).slice().reverse().map(x=>[fmt(x.createdAt),esc(x.title||'-'),esc(String(x.format||'').toUpperCase()),esc(x.fileName||'-'),`<span class="rpt-badge">${esc(x.storageStatus||'stored')}</span>`,esc(x.r2Key||'-')]);return page('Arsip R2','Simpan hasil final ke Cloudflare R2.',`<div class="rpt-builder"><form onsubmit="ReportPhase4.uploadR2(event)"><label class="label">Pilih file laporan</label><input class="input" type="file" name="file" required><label class="label" style="margin-top:10px">Project</label><select class="select" name="projectId"><option value="">Umum</option>${(db.projects||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.code||p.id)} — ${esc(p.name)}</option>`).join('')}</select><button class="btn btn-primary" style="margin-top:12px">Simpan ke R2</button></form><div id="r4-r2-status" class="rpt-warning">Data API masih dapat terkunci selama UAT.</div></div>${table(['Waktu','Laporan','Format','File','Status','R2 Key'],rows)}`)}
function render(force=false){if(!ROUTES.has(location.hash))return false;const root=document.querySelector('.content');if(!root)return false;if(!force&&root.dataset.reportPhase4Route===location.hash&&root.querySelector('.rpt-wrap'))return true;let html=templatesPage();if(location.hash==='#/reports/approvals')html=approvalsPage();else if(location.hash==='#/reports/schedules')html=schedulesPage();else if(location.hash==='#/reports/archive')html=archivePage();root.innerHTML=html;root.dataset.reportPhase4Route=location.hash;const title=document.querySelector('.topbar-title');if(title)title.textContent='Laporan';return true}
function nextRun(frequency,time){const d=new Date();const [h,m]=String(time||'08:00').split(':').map(Number);d.setHours(h,m,0,0);if(d<=new Date())d.setDate(d.getDate()+1);if(frequency==='weekly')d.setDate(d.getDate()+7);if(frequency==='monthly')d.setMonth(d.getMonth()+1,1);return d.toISOString()}
window.ReportPhase4={saveSettings(e){e.preventDefault();if(!manager())return;const db=read(),f=Object.fromEntries(new FormData(e.target));db.reportSettings={...db.reportSettings,...f,nextNumber:Math.max(1,Number(f.nextNumber||1)),updatedAt:now()};audit(db,'update','report_settings','primary','Memperbarui identitas dokumen');write(db);render(true)},newTemplate(){if(!manager())return;const name=prompt('Nama template');if(!name)return;const db=read();db.reportTemplates.push({id:uid('TPL'),name,type:'custom',layout:'portrait',includeCompanyLogo:true,includeClientLogo:false,requireApproval:false,status:'active',columns:[],createdAt:now()});write(db);render(true)},editTemplate(id){if(!manager())return;const db=read(),t=db.reportTemplates.find(x=>x.id===id);if(!t)return;const name=prompt('Nama template',t.name);if(!name)return;t.name=name;t.layout=t.layout==='portrait'?'landscape':'portrait';t.updatedAt=now();write(db);render(true)},requestApproval(){const title=prompt('Judul dokumen yang diajukan');if(!title)return;const db=read(),item={id:uid('APR'),documentNumber:number(db),title,status:'pending',requestedAt:now(),requestedBy:account().id,requestedByName:account().name||account().email};db.reportApprovals.push(item);db.reportSettings.nextNumber=Number(db.reportSettings.nextNumber||1)+1;write(db);render(true)},approve(id){if(!manager())return;const db=read(),a=db.reportApprovals.find(x=>x.id===id);if(!a)return;a.status='approved';a.approvedAt=now();a.approvedByName=account().name||account().email;write(db);render(true)},reject(id){if(!manager())return;const db=read(),a=db.reportApprovals.find(x=>x.id===id);if(!a)return;a.status='rejected';a.reason=prompt('Alasan penolakan')||'Tidak disetujui';write(db);render(true)},saveSchedule(e){e.preventDefault();if(!manager())return;const f=Object.fromEntries(new FormData(e.target)),db=read();db.reportSchedules.push({id:uid('SCH'),...f,status:'active',filters:{},nextRunAt:nextRun(f.frequency,f.time),createdAt:now(),createdBy:account().id});write(db);render(true)},toggleSchedule(id){if(!manager())return;const db=read(),s=db.reportSchedules.find(x=>x.id===id);if(!s)return;s.status=s.status==='active'?'paused':'active';write(db);render(true)},async uploadR2(e){e.preventDefault();const file=e.target.file.files[0],status=document.getElementById('r4-r2-status');if(!file)return;status.textContent='Mengunggah...';try{const projectId=e.target.projectId.value||'general';const res=await fetch(`/api/files?${new URLSearchParams({name:file.name,projectId,ownerId:account().id||'anonymous',category:'report'})}`,{method:'POST',headers:{'content-type':file.type||'application/octet-stream'},body:file});const data=await res.json();if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);status.textContent=`Tersimpan: ${data.key}`}catch(error){status.textContent=`Upload gagal: ${error.message}`}}};
function sync(){render(false)}
window.addEventListener('hashchange',()=>setTimeout(sync,40));
window.addEventListener('proqtrack:db-updated',()=>{if(ROUTES.has(location.hash))render(true)});
init();setTimeout(sync,60);export {};