const DB_KEY = 'proqtrack_db_v6';
const DB_V7_KEY = 'proqtrack_db_v7';
const EXPORT_ROUTE = '#/reports/exports';

const esc = (v='') => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const xml = (v='') => String(v ?? '').replace(/[<>&'"]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c]));
const val = (o, keys, fallback='') => keys.map(k => o?.[k]).find(v => v !== undefined && v !== null && v !== '') ?? fallback;
const dateOf = o => String(val(o,['date','attendanceDate','visitDate','createdAt','checkInAt','timestamp','updatedAt'],'')).slice(0,10);
const statusOf = o => String(val(o,['status','attendanceStatus','visitStatus'],'-'));
const readDB = () => { try { return JSON.parse(localStorage.getItem(DB_KEY) || localStorage.getItem(DB_V7_KEY) || '{}'); } catch { return {}; } };
const writeDB = db => { const text=JSON.stringify(db); localStorage.setItem(DB_KEY,text); localStorage.setItem(DB_V7_KEY,text); window.dispatchEvent(new CustomEvent('proqtrack:db-updated')); };
const account = () => window.FT?.state?.account || null;
const now = () => new Date().toISOString();
const fmtDate = v => v ? new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)) : '-';
const safeName = v => String(v || 'laporan').trim().replace(/[^a-zA-Z0-9-_]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').toLowerCase();

function ensureArrays(db){ for(const key of ['reportJobs','reportExports','auditLogs']) if(!Array.isArray(db[key])) db[key]=[]; }
function filters(){ const form=document.getElementById('rptFilterForm'); return form ? Object.fromEntries(new FormData(form).entries()) : {}; }
function scope(db){
  const r=String(account()?.role||'employee').toLowerCase();
  if(r==='manager'||r==='admin') return {employeeIds:null,projectIds:null};
  const me=account()?.employeeId;
  const assignments=db.projectAssignments||[];
  const own=assignments.filter(a=>a.employeeId===me&&a.status==='active').map(a=>a.projectId);
  if(r==='supervisor'){
    const employeeIds=new Set([me]);
    assignments.filter(a=>own.includes(a.projectId)&&a.status==='active'&&(!a.supervisorId||a.supervisorId===me||a.employeeId===me)).forEach(a=>employeeIds.add(a.employeeId));
    return {employeeIds,projectIds:new Set(own)};
  }
  return {employeeIds:new Set([me]),projectIds:new Set(own)};
}

function buildReport(f={}){
  const db=readDB();
  const access=scope(db);
  const employees=(db.employees||[]).filter(e=>!access.employeeIds||access.employeeIds.has(e.id));
  let projects=(db.projects||[]).filter(p=>!access.projectIds||access.projectIds.has(p.id));
  if(f.clientId) projects=projects.filter(p=>p.clientId===f.clientId);
  if(f.projectId) projects=projects.filter(p=>p.id===f.projectId);
  const employeeIds=new Set(employees.map(e=>e.id));
  const projectIds=new Set(projects.map(p=>p.id));
  const employeeName=id=>employees.find(e=>e.id===id)?.name||id||'-';
  const projectName=id=>projects.find(p=>p.id===id)?.name||id||'-';
  const clientName=id=>(db.clients||[]).find(c=>c.id===id)?.name||id||'-';
  const inPeriod=row=>{const d=dateOf(row);return(!f.start||!d||d>=f.start)&&(!f.end||!d||d<=f.end);};
  const allowed=row=>{const eid=val(row,['employeeId','userId']);const pid=val(row,['projectId']);return(!eid||employeeIds.has(eid))&&(!pid||projectIds.has(pid))&&(!f.employeeId||eid===f.employeeId)&&(!f.projectId||pid===f.projectId)&&inPeriod(row);};
  const assignments=(db.projectAssignments||[]).filter(a=>(!access.projectIds||access.projectIds.has(a.projectId))&&(!access.employeeIds||access.employeeIds.has(a.employeeId)));
  const type=f.type||'attendance'; let title='Laporan ProQTrack'; let headers=[]; let rows=[]; let photos=[];
  if(type==='attendance'){
    title='Laporan Kehadiran'; headers=['Tanggal','Karyawan','Project','Status','Jam Masuk','Jam Pulang','Lokasi'];
    rows=(db.attendance||[]).filter(allowed).filter(r=>!f.status||statusOf(r)===f.status).map(r=>[fmtDate(dateOf(r)),employeeName(val(r,['employeeId','userId'])),projectName(r.projectId),statusOf(r),val(r,['checkIn','checkInAt','timeIn'],'-'),val(r,['checkOut','checkOutAt','timeOut'],'-'),val(r,['area','locationName','location'],'-')]);
  } else if(type==='employees'){
    title='Laporan Karyawan'; headers=['ID','Nama','Jabatan','Area','Status','Project Aktif'];
    rows=employees.filter(e=>!f.employeeId||e.id===f.employeeId).filter(e=>!f.status||e.status===f.status).map(e=>[e.id,e.name,val(e,['role','jobRole'],'-'),val(e,['area','region'],'-'),e.status||'-',assignments.filter(a=>a.employeeId===e.id&&a.status==='active').map(a=>projectName(a.projectId)).join(', ')||'-']);
  } else if(type==='projects'){
    title='Laporan Klien & Project'; headers=['Kode','Project','Klien','Status','Mulai','Selesai','HC Aktif','Jumlah Visit'];
    rows=projects.filter(p=>!f.status||p.status===f.status).map(p=>[p.code||p.id,p.name,clientName(p.clientId),p.status||'-',fmtDate(p.startDate),fmtDate(p.endDate),assignments.filter(a=>a.projectId===p.id&&a.status==='active').length,(db.visits||[]).filter(v=>v.projectId===p.id&&inPeriod(v)).length]);
  } else if(type==='field'){
    title='Laporan Aktivitas Lapangan'; headers=['Tanggal','Aktivitas','Karyawan','Project','Detail','Status'];
    const photoSource=db.fieldPhotos||db.photos||[];
    rows=[...(db.visits||[]).filter(allowed).map(r=>[fmtDate(dateOf(r)),'Kunjungan',employeeName(val(r,['employeeId','userId'])),projectName(r.projectId),val(r,['outletName','title','notes'],'-'),statusOf(r)]),...photoSource.filter(allowed).map(r=>[fmtDate(dateOf(r)),'Foto',employeeName(val(r,['employeeId','userId'])),projectName(r.projectId),val(r,['title','category','photoType'],'-'),statusOf(r)])];
    photos=photoSource.filter(allowed);
  } else {
    title='Laporan Supervisor'; headers=['Supervisor','Anggota','Project','Record Absensi','Kehadiran'];
    const supervisors=employees.filter(e=>/supervisor/i.test(String(e.role||''))||assignments.some(a=>a.employeeId===e.id&&a.roleOnProject==='supervisor'));
    rows=supervisors.map(s=>{const team=new Set(assignments.filter(a=>a.supervisorId===s.id&&a.status==='active').map(a=>a.employeeId));const prj=new Set(assignments.filter(a=>(a.employeeId===s.id||a.supervisorId===s.id)&&a.status==='active').map(a=>a.projectId));const att=(db.attendance||[]).filter(a=>team.has(a.employeeId)&&inPeriod(a));const present=att.filter(a=>/present|hadir|late|terlambat/i.test(statusOf(a))).length;return[s.name,team.size,prj.size,att.length,att.length?`${Math.round(present/att.length*100)}%`:'-'];});
  }
  return {db,type,title,headers,rows,photos,filters:f,generatedAt:now()};
}

function fileName(report,ext){const period=[report.filters.start,report.filters.end].filter(Boolean).join('_')||new Date().toISOString().slice(0,10);return `${safeName(report.title)}_${period}.${ext}`;}
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function csvText(report){const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;const rows=[['Judul',report.title],['Dibuat',new Date(report.generatedAt).toLocaleString('id-ID')],['Periode',`${report.filters.start||'-'} s.d. ${report.filters.end||'-'}`],[],report.headers,...report.rows];return '\ufeff'+rows.map(r=>r.map(q).join(',')).join('\r\n');}
function loadScript(src,globalName){return new Promise((resolve,reject)=>{if(window[globalName])return resolve(window[globalName]);const existing=document.querySelector(`script[data-lib="${globalName}"]`);if(existing){existing.addEventListener('load',()=>resolve(window[globalName]),{once:true});existing.addEventListener('error',reject,{once:true});return;}const s=document.createElement('script');s.src=src;s.async=true;s.dataset.lib=globalName;s.onload=()=>window[globalName]?resolve(window[globalName]):reject(new Error(`${globalName} gagal dimuat`));s.onerror=()=>reject(new Error(`Gagal memuat ${globalName}`));document.head.appendChild(s);});}
async function getJSZip(){return loadScript('https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js','JSZip');}
async function getJsPDF(){await loadScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js','jspdf');return window.jspdf.jsPDF;}
function colName(n){let out='';while(n>0){n--;out=String.fromCharCode(65+n%26)+out;n=Math.floor(n/26);}return out;}
async function xlsxBlob(report){const JSZip=await getJSZip();const zip=new JSZip();const rows=[report.headers,...report.rows];const sheet=rows.map((row,r)=>`<row r="${r+1}">${row.map((v,c)=>{const ref=`${colName(c+1)}${r+1}`;return typeof v==='number'?`<c r="${ref}"><v>${v}</v></c>`:`<c r="${ref}" t="inlineStr"><is><t>${xml(v)}</t></is></c>`;}).join('')}</row>`).join('');zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');zip.folder('xl').file('workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Laporan" sheetId="1" r:id="rId1"/></sheets></workbook>');zip.folder('xl').folder('_rels').file('workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');zip.folder('xl').folder('worksheets').file('sheet1.xml',`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${sheet}</sheetData></worksheet>`);return zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
async function docxBlob(report){const JSZip=await getJSZip();const zip=new JSZip();const p=(t,b=false)=>`<w:p><w:r>${b?'<w:rPr><w:b/></w:rPr>':''}<w:t xml:space="preserve">${xml(t)}</w:t></w:r></w:p>`;const table=[report.headers,...report.rows].map((row,i)=>`<w:tr>${row.map(v=>`<w:tc><w:p><w:r>${i===0?'<w:rPr><w:b/></w:rPr>':''}<w:t>${xml(v)}</w:t></w:r></w:p></w:tc>`).join('')}</w:tr>`).join('');const doc=`<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${p(report.title,true)}${p(`Dibuat: ${new Date(report.generatedAt).toLocaleString('id-ID')}`)}${p(`Periode: ${report.filters.start||'-'} s.d. ${report.filters.end||'-'}`)}<w:tbl>${table}</w:tbl><w:sectPr/></w:body></w:document>`;zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');zip.folder('word').file('document.xml',doc);zip.folder('word').folder('_rels').file('document.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>');return zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});}
async function pdfBlob(report){const jsPDF=await getJsPDF();const doc=new jsPDF({orientation:report.headers.length>6?'landscape':'portrait',unit:'pt',format:'a4'});const width=doc.internal.pageSize.getWidth(),height=doc.internal.pageSize.getHeight(),margin=32;let y=40;doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text(report.title,margin,y);y+=18;doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(`Periode: ${report.filters.start||'-'} s.d. ${report.filters.end||'-'}`,margin,y);y+=16;const cw=(width-margin*2)/report.headers.length;const draw=(row,head=false)=>{const lines=row.map(v=>doc.splitTextToSize(String(v??''),cw-6));const rh=Math.max(18,Math.max(...lines.map(x=>x.length))*9+5);if(y+rh>height-margin){doc.addPage();y=margin;}if(head){doc.setFillColor(245,245,245);doc.rect(margin,y,cw*row.length,rh,'F');doc.setFont('helvetica','bold');}else doc.setFont('helvetica','normal');doc.setFontSize(7);row.forEach((v,i)=>{doc.rect(margin+i*cw,y,cw,rh);doc.text(lines[i],margin+i*cw+3,y+10);});y+=rh;};draw(report.headers,true);report.rows.forEach(r=>draw(r));return doc.output('blob');}
function printView(report){const popup=window.open('','_blank');if(!popup)throw new Error('Popup diblokir browser');popup.opener=null;popup.document.open();popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(report.title)}</title><style>body{font-family:Arial,sans-serif;padding:28px;color:#111}h1{font-size:22px;margin:0 0 5px}.meta{font-size:12px;color:#555;margin-bottom:18px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #ccc;padding:7px;text-align:left;vertical-align:top}th{background:#f2f2f2}@media print{body{padding:0}}</style></head><body><h1>${esc(report.title)}</h1><div class="meta">Periode: ${esc(report.filters.start||'-')} s.d. ${esc(report.filters.end||'-')}<br>Dibuat: ${esc(new Date(report.generatedAt).toLocaleString('id-ID'))}</div><table><thead><tr>${report.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${report.rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`);popup.document.close();popup.focus();setTimeout(()=>popup.print(),350);}
async function addPhotos(zip,report){const folder=zip.folder('foto-pendukung');const manifest=[];for(const [i,p] of report.photos.slice(0,50).entries()){const src=val(p,['dataUrl','imageData','url','src','photoUrl']);if(!src)continue;try{const res=await fetch(src);if(!res.ok)throw new Error(`HTTP ${res.status}`);const blob=await res.blob();const ext=blob.type.includes('png')?'png':blob.type.includes('webp')?'webp':'jpg';const name=`${String(i+1).padStart(3,'0')}-${safeName(val(p,['title','category','photoType'],'foto'))}.${ext}`;folder.file(name,blob);manifest.push({name,employeeId:p.employeeId||'',projectId:p.projectId||'',date:dateOf(p)});}catch(error){manifest.push({source:src,error:String(error.message||error)});}}folder.file('manifest.json',JSON.stringify(manifest,null,2));}
function record(report,format,name,status='completed',error=''){const db=readDB();ensureArrays(db);const id=`RPE-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;const createdAt=now();db.reportJobs.push({id:`RPJ-${Date.now()}`,reportType:report.type,format,status,createdAt,completedAt:status==='completed'?createdAt:null,error});db.reportExports.push({id,type:report.type,title:report.title,format,fileName:name,filters:report.filters,rowCount:report.rows.length,status,error,createdAt,createdBy:account()?.id||null,createdByName:account()?.email||account()?.name||'-'});db.auditLogs.push({id:`AUD-${Date.now()}`,createdAt,actorId:account()?.id,actorName:account()?.email||account()?.name||'-',action:status==='completed'?'export':'export_failed',entityType:'report',entityId:id,description:`${format.toUpperCase()} ${report.title} (${report.rows.length} baris)`});writeDB(db);}
async function run(format){const report=buildReport(filters());if(!report.rows.length){window.showToast?.('Tidak ada data untuk diekspor','error');return;}const btn=document.querySelector(`[data-export-format="${format}"]`);const original=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Memproses...';}let name='';try{if(format==='csv'){name=fileName(report,'csv');download(new Blob([csvText(report)],{type:'text/csv;charset=utf-8'}),name);}else if(format==='xlsx'){name=fileName(report,'xlsx');download(await xlsxBlob(report),name);}else if(format==='docx'){name=fileName(report,'docx');download(await docxBlob(report),name);}else if(format==='pdf'){name=fileName(report,'pdf');download(await pdfBlob(report),name);}else if(format==='print'){name=fileName(report,'html');printView(report);}else if(format==='zip'){name=fileName(report,'zip');const JSZip=await getJSZip();const zip=new JSZip();zip.file(fileName(report,'csv'),csvText(report));zip.file(fileName(report,'xlsx'),await xlsxBlob(report));zip.file(fileName(report,'docx'),await docxBlob(report));zip.file(fileName(report,'pdf'),await pdfBlob(report));zip.file('metadata.json',JSON.stringify({title:report.title,filters:report.filters,generatedAt:report.generatedAt,rowCount:report.rows.length},null,2));if(report.type==='field'&&report.photos.length)await addPhotos(zip,report);download(await zip.generateAsync({type:'blob'}),name);}record(report,format,name);window.showToast?.(`${format.toUpperCase()} berhasil dibuat`,'success');renderHistory();}catch(error){record(report,format,name||'-','failed',String(error.message||error));window.showToast?.(`Export gagal: ${error.message||error}`,'error');}finally{if(btn){btn.disabled=false;btn.textContent=original;}}}
function controls(){return `<div class="rpt-export-panel"><div><strong>Export Laporan</strong><p>Gunakan filter aktif untuk menghasilkan datasheet atau dokumen.</p></div><div class="rpt-export-actions"><button class="btn btn-secondary btn-sm" data-export-format="csv" onclick="ReportExport.run('csv')">CSV</button><button class="btn btn-secondary btn-sm" data-export-format="xlsx" onclick="ReportExport.run('xlsx')">XLSX</button><button class="btn btn-secondary btn-sm" data-export-format="docx" onclick="ReportExport.run('docx')">DOCX</button><button class="btn btn-secondary btn-sm" data-export-format="pdf" onclick="ReportExport.run('pdf')">PDF</button><button class="btn btn-secondary btn-sm" data-export-format="print" onclick="ReportExport.run('print')">Print</button><button class="btn btn-primary btn-sm" data-export-format="zip" onclick="ReportExport.run('zip')">ZIP + Lampiran</button></div></div>`;}
function inject(){const builder=document.querySelector('.rpt-builder');if(builder&&!builder.querySelector('.rpt-export-panel'))builder.insertAdjacentHTML('beforeend',controls());document.querySelectorAll('.rpt-nav').forEach(nav=>{if(!nav.querySelector(`[href="${EXPORT_ROUTE}"]`))nav.insertAdjacentHTML('beforeend',`<a href="${EXPORT_ROUTE}" class="${location.hash===EXPORT_ROUTE?'active':''}">Riwayat Ekspor</a>`);});}
function historyHTML(){const db=readDB();ensureArrays(db);const rows=db.reportExports.slice().reverse();const body=rows.length?`<div class="rpt-table-wrap"><table class="rpt-table"><thead><tr><th>Waktu</th><th>Laporan</th><th>Format</th><th>Baris</th><th>Status</th><th>File</th><th>Dibuat Oleh</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(new Date(r.createdAt).toLocaleString('id-ID'))}</td><td>${esc(r.title)}</td><td><span class="rpt-badge">${esc(String(r.format).toUpperCase())}</span></td><td>${esc(r.rowCount)}</td><td><span class="rpt-badge ${r.status==='failed'?'rpt-badge-error':''}">${esc(r.status)}</span>${r.error?`<div class="rpt-error-text">${esc(r.error)}</div>`:''}</td><td>${esc(r.fileName)}</td><td>${esc(r.createdByName||'-')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="rpt-empty">Belum ada riwayat ekspor.</div>';return `<div class="rpt-wrap"><div class="rpt-nav"><a href="#/reports">Ringkasan</a><a href="#/reports/attendance">Kehadiran</a><a href="#/reports/employees">Karyawan</a><a href="#/reports/projects">Klien & Project</a><a href="#/reports/field">Aktivitas Lapangan</a><a href="#/reports/supervisors">Supervisor</a><a href="#/reports/audit">Audit</a><a class="active" href="${EXPORT_ROUTE}">Riwayat Ekspor</a></div><div class="rpt-page-title"><div><h3>Riwayat Ekspor</h3><p style="color:var(--gray-500);font-size:12px">Jejak file yang dihasilkan pada perangkat ini.</p></div><button class="btn btn-secondary btn-sm" onclick="ReportExport.clearHistory()">Bersihkan Riwayat</button></div>${body}</div>`;}
function renderHistory(){if(location.hash!==EXPORT_ROUTE)return false;const root=document.querySelector('.content');if(!root)return false;root.innerHTML=historyHTML();root.dataset.reportsRoute=EXPORT_ROUTE;const title=document.querySelector('.topbar-title');if(title)title.textContent='Laporan';const subtitle=document.querySelector('.topbar-subtitle');if(subtitle){subtitle.textContent='Riwayat ekspor dokumen dan datasheet';subtitle.style.display='block';}return true;}
function styles(){if(document.getElementById('reports-export-css'))return;const s=document.createElement('style');s.id='reports-export-css';s.textContent='.rpt-export-panel{margin-top:14px;padding:14px;border:1px solid var(--gray-200);border-radius:12px;background:var(--gray-50);display:flex;justify-content:space-between;gap:14px;align-items:center}.rpt-export-panel strong{display:block;font-size:14px}.rpt-export-panel p{font-size:11px;color:var(--gray-500);margin:2px 0 0}.rpt-export-actions{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.rpt-export-actions button:disabled{opacity:.6;cursor:wait}.rpt-badge-error{background:#fef2f2;color:#b91c1c}.rpt-error-text{font-size:10px;color:#b91c1c;max-width:240px;margin-top:3px}@media(max-width:760px){.rpt-export-panel{align-items:stretch;flex-direction:column}.rpt-export-actions{justify-content:flex-start}.rpt-export-actions .btn{flex:1}}';document.head.appendChild(s);}
window.ReportExport={run,clearHistory(){if(!confirm('Hapus seluruh riwayat ekspor pada browser ini?'))return;const db=readDB();ensureArrays(db);db.reportExports=[];db.reportJobs=[];writeDB(db);renderHistory();window.showToast?.('Riwayat ekspor dibersihkan','success');}};
let queued=false;function sync(){queued=false;styles();if(!renderHistory())inject();}new MutationObserver(()=>{if(!queued){queued=true;requestAnimationFrame(sync);}}).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(sync));window.addEventListener('storage',sync);sync();export {};
