import { defaultPortrait } from './lib/avatars.js';

const DB_KEYS=['proqtrack_db_v6','proqtrack_db_v7'];

function readDB(){try{return JSON.parse(localStorage.getItem(DB_KEYS[0])||localStorage.getItem(DB_KEYS[1])||'{}')||{};}catch{return{};}}
function writeDB(db,reason='employee-avatar'){const text=JSON.stringify(db);DB_KEYS.forEach(k=>localStorage.setItem(k,text));window.dispatchEvent(new CustomEvent('proqtrack:db-updated',{detail:{reason}}));}
function backfillPortraits(){const db=readDB();let changed=false;for(const employee of db.employees||[]){if(employee.photo)continue;employee.photo=defaultPortrait(employee);employee.photoSource='default';employee.photoUpdatedAt=new Date().toISOString();changed=true;}if(changed)writeDB(db,'employee-avatar-backfill');}
function ensureStyles(){if(document.getElementById('employee-avatar-css'))return;const style=document.createElement('style');style.id='employee-avatar-css';style.textContent=`#empTable .avatar{width:34px!important;height:34px!important;flex:0 0 34px!important;border-radius:10px!important;background-size:cover!important;background-position:center!important;box-shadow:0 1px 4px rgba(15,23,42,.12)}#empTable td:first-child>div{gap:9px!important}.employee-photo-editor{grid-column:1/-1;padding:12px;border:1px solid var(--gray-200);border-radius:14px;background:var(--gray-50);display:grid;grid-template-columns:64px 1fr;gap:12px;align-items:center}.employee-photo-preview{width:64px;height:64px;border-radius:16px;object-fit:cover;background:#fff;border:1px solid var(--gray-200)}.employee-photo-help{font-size:11px;color:var(--gray-400);margin-top:5px;line-height:1.45}@media(max-width:640px){.employee-photo-editor{grid-template-columns:52px 1fr}.employee-photo-preview{width:52px;height:52px;border-radius:13px}}`;document.head.appendChild(style);}
function injectUploadControl(id){const form=document.querySelector('form[onsubmit*="FT.updateEmployee"]');if(!form||form.querySelector('[data-employee-photo-upload]')||form.querySelector('.emp-photo-field'))return;const employee=(readDB().employees||[]).find(e=>e.id===id);const editor=document.createElement('div');editor.className='employee-photo-editor';editor.dataset.employeePhotoUpload='1';editor.innerHTML=`<img class="employee-photo-preview" alt="Preview foto karyawan" src="${employee?.photo||defaultPortrait(employee)}"><div><label class="label">Upload Foto Karyawan</label><input class="input" type="file" name="photoUpload" accept="image/jpeg,image/png,image/webp"><div class="employee-photo-help">JPG, PNG, atau WebP. Foto dikompres otomatis dan menggantikan avatar lama.</div><button type="button" class="btn btn-secondary btn-sm" style="margin-top:8px" data-default-photo>Gunakan avatar bawaan</button></div>`;const firstRow=form.querySelector('.form-row');firstRow?.before(editor);const input=editor.querySelector('input'),preview=editor.querySelector('img');input.addEventListener('change',()=>{const file=input.files?.[0];if(file)preview.src=URL.createObjectURL(file);});editor.querySelector('[data-default-photo]').addEventListener('click',()=>{input.value='';input.dataset.useDefault='1';preview.src=defaultPortrait(employee);});}
function installEditHook(){if(!window.FT?.editEmployee||window.FT.editEmployee.__photoWrapped)return false;const original=window.FT.editEmployee;const wrapped=function(id){const result=original.call(this,id);requestAnimationFrame(()=>injectUploadControl(id));return result;};wrapped.__photoWrapped=true;window.FT.editEmployee=wrapped;return true;}
function installUpdateHook(){if(!window.FT?.updateEmployee||window.FT.updateEmployee.__photoWrapped)return false;const original=window.FT.updateEmployee;const wrapped=async function(event,id){const form=event?.target,input=form?.querySelector('input[name="photoUpload"]');if(!input||(!input.files?.[0]&&!input.dataset.useDefault))return original.call(this,event,id);event.preventDefault();try{const employee=(readDB().employees||[]).find(e=>e.id===id);const photo=input.files?.[0]?await window.FT.compressImage(input.files[0],320,0.8):defaultPortrait(employee);let hidden=form.querySelector('input[type="hidden"][name="photo"]');if(!hidden){hidden=document.createElement('input');hidden.type='hidden';hidden.name='photo';form.appendChild(hidden);}hidden.value=photo;return original.call(this,event,id);}catch(error){window.showToast?.(`Foto gagal diproses: ${error.message||error}`,'error');}};wrapped.__photoWrapped=true;window.FT.updateEmployee=wrapped;return true;}
function install(){ensureStyles();backfillPortraits();let attempts=0;const timer=setInterval(()=>{attempts++;if((installEditHook()&&installUpdateHook())||attempts>100)clearInterval(timer);},50);}
install();
export {};
