import { icon, iconSvg, ROUTE_ICONS as routeIcons } from '../assets/icons.js';
const labelIcons={'Total Karyawan':'employees','Karyawan aktif':'employees','Kunjungan Hari Ini':'visits','Kunjungan hari ini':'visits','Kunjungan tim':'visits','Stok Menipis':'stocks','Stok menipis':'stocks','Ijin/Cuti Pending':'leaves','Cuti pending':'leaves','Ijin menunggu':'leaves','Total Foto':'photos','Lokasi':'pin','Produk':'products','Rak / Display':'stocks','Anggota tim':'team','Sedang di lapangan':'tracking','Project Aktif':'briefcase'};
const graphLabels=new Set(['Kunjungan Hari Ini']);
const pictographic=/\p{Extended_Pictographic}/gu;
function db(){try{return JSON.parse(localStorage.getItem('proqtrack_db_v6')||'null')}catch{return null}}
function stripEmoji(root){root.querySelectorAll('*').forEach(el=>{if(el.closest('.mq-hello,.mq-home'))return;if(el.children.length||['SCRIPT','STYLE','SVG','PATH'].includes(el.tagName))return;const text=el.textContent||'';if(pictographic.test(text))el.textContent=text.replace(pictographic,'').replace(/\uFE0F/g,'').replace(/\s{2,}/g,' ').trim()})}
function orgBrand(){try{const s=JSON.parse(localStorage.getItem('proqtrack_db_v6')||'{}').appSettings||{};return{name:s.companyName||'ProQTrack',logo:s.companyLogo||''}}catch{return{name:'ProQTrack',logo:''}}}
function paintLogos(root){const brand=orgBrand();root.querySelectorAll('.login-logo,.sidebar-logo').forEach(el=>{el.setAttribute('aria-label',brand.name);if(!brand.logo){el.querySelectorAll('img,iframe').forEach(node=>node.remove());el.classList.remove('has-org-logo');return}let img=el.querySelector('img');if(!img){el.textContent='';img=document.createElement('img');img.alt=brand.name;el.appendChild(img)}if(img.getAttribute('src')!==brand.logo)img.setAttribute('src',brand.logo);el.classList.add('has-org-logo')})}
function paintNav(root){root.querySelectorAll('.nav-item').forEach(a=>{const holder=a.querySelector('.nav-icon');if(!holder)return;const name=routeIcons[a.getAttribute('href')]||holder.dataset.icon||'home';holder.innerHTML=iconSvg(name);holder.dataset.vector='1';holder.dataset.icon=name})}
function spark(seed=0){const sets=[[31,25,29,20,22,13,16],[32,30,24,27,18,21,12]];const p=sets[seed%sets.length];return `<svg class="phase0-sparkline" viewBox="0 0 96 42" preserveAspectRatio="none"><path class="area" d="M2 ${p[0]} L17 ${p[1]} L32 ${p[2]} L47 ${p[3]} L62 ${p[4]} L77 ${p[5]} L94 ${p[6]} L94 42 L2 42Z"/><path class="line" d="M2 ${p[0]} L17 ${p[1]} L32 ${p[2]} L47 ${p[3]} L62 ${p[4]} L77 ${p[5]} L94 ${p[6]}"/></svg>`}
function paintStats(root){root.querySelectorAll('.stat-card').forEach((card,i)=>{if(card.dataset.phase0==='2')return;const label=card.querySelector('.stat-label')?.textContent.trim()||'';const holder=card.querySelector('.stat-icon');if(holder)holder.innerHTML=icon(labelIcons[label]||'chart');if(graphLabels.has(label))card.insertAdjacentHTML('beforeend',spark(i));else card.classList.add('phase0-stat-clean');card.dataset.phase0='2'})}
function paintEmpty(root){root.querySelectorAll('.empty-icon').forEach(el=>{if(el.dataset.vector==='1')return;el.innerHTML=icon('search');el.dataset.vector='1'})}
function paintButtons(root){root.querySelectorAll('button').forEach(btn=>{if(btn.dataset.vector==='1'||btn.querySelector('svg'))return;const t=btn.textContent.trim().toLowerCase();const n=t.includes('hapus')?'trash':t.includes('foto')?'camera':t.includes('tambah')||t.startsWith('+')?'plus':t.includes('unduh')||t.includes('export')?'download':null;if(!n)return;btn.textContent=btn.textContent.replace(pictographic,'').replace(/^\+\s*/,'').trim();btn.insertAdjacentHTML('afterbegin',icon(n,'phase0-button-icon'));btn.dataset.vector='1'})}
function addDashboardGraph(root){const title=[...root.querySelectorAll('.card-title')].find(x=>x.textContent.includes('Progress Kunjungan'));if(!title)return;const card=title.closest('.card');if(!card||card.dataset.chart==='2')return;card.insertAdjacentHTML('beforeend','<div class="phase0-chart" aria-label="Grafik aktivitas tujuh hari"><div class="phase0-chart-bar" style="height:35%"></div><div class="phase0-chart-bar" style="height:52%"></div><div class="phase0-chart-bar" style="height:44%"></div><div class="phase0-chart-bar" style="height:68%"></div><div class="phase0-chart-bar" style="height:61%"></div><div class="phase0-chart-bar" style="height:82%"></div><div class="phase0-chart-bar" style="height:74%"></div></div><div class="phase0-chart-labels"><span>Sen</span><span>Sel</span><span>Rab</span><span>Kam</span><span>Jum</span><span>Sab</span><span>Min</span></div>');card.dataset.chart='2'}
function paintAvatars(root){const data=db();if(!data?.employees)return;const byInitial=new Map(data.employees.map(e=>[e.name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase(),e]));root.querySelectorAll('.avatar,.sidebar-avatar').forEach(el=>{if(el.querySelector('img'))return;const emp=byInitial.get(el.textContent.trim().toUpperCase());if(emp?.photo){const alt=String(emp.name||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));el.innerHTML=`<img src="${emp.photo}" alt="${alt}">`;el.classList.add('phase0-photo-avatar')}})}
function addPortfolio(root){const hash=location.hash||'#/';if(hash!=='#'&&hash!=='#/')return;if(root.querySelector('.mq-home'))return;const title=[...root.querySelectorAll('.topbar-title')].find(x=>['Organization Home','Team Home','Home'].includes(x.textContent.trim()));if(!title)return;const content=root.querySelector('.content');if(!content||content.querySelector('.phase0-portfolio'))return;const data=db();if(!data?.clients?.length||!data?.projects?.length)return;const clients=data.clients.filter(c=>c.status!=='inactive');const projects=data.projects.filter(p=>!['completed','cancelled'].includes(p.status));const assignments=data.projectAssignments||[];const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const section=document.createElement('section');section.className='phase0-portfolio';section.innerHTML=`<div class="phase0-section-head"><div><h2>Portofolio Aktif</h2><p>${clients.length} klien, ${projects.length} project, dan ${(data.employees||[]).filter(e=>e.status==='active').length} tenaga lapangan</p></div></div><div class="phase0-client-strip">${clients.slice(0,10).map(c=>`<div class="phase0-client-logo"><img src="${c.logoUrl||c.logo||''}" alt="${esc(c.name)}"></div>`).join('')}</div><div class="phase0-project-grid">${projects.slice(0,5).map(p=>{const c=clients.find(x=>x.id===p.clientId);const count=assignments.filter(a=>a.projectId===p.id&&a.status==='active').length;return `<article class="phase0-project-card"><div class="phase0-project-icon">${icon('briefcase')}</div><div><strong>${esc(p.name)}</strong><span>${esc(c?.name||'')} · ${esc(p.area||p.region||'')}</span></div><b>${count} HC</b></article>`}).join('')}</div>`;content.prepend(section)}
let queued=false;function enhance(){queued=false;const root=document;paintLogos(root);paintNav(root);paintStats(root);paintEmpty(root);paintButtons(root);paintAvatars(root);addDashboardGraph(root);addPortfolio(root);stripEmoji(root)}
new MutationObserver(()=>{if(!queued){queued=true;requestAnimationFrame(enhance)}}).observe(document.documentElement,{subtree:true,childList:true});enhance();
let deferredPrompt;const install=document.createElement('button');install.className='pwa-install';install.innerHTML=`${icon('download')} Pasang ProQTrack`;document.body.appendChild(install);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;install.classList.add('show')});install.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;install.classList.remove('show')});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
