const paths={home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/>',tracking:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a8 8 0 1 0-14.8 0"/><path d="M12 22v-3"/><path d="M4.9 19.1 7 17"/><path d="m17 17 2.1 2.1"/>',visits:'<path d="M9 5h11"/><path d="M9 12h11"/><path d="M9 19h11"/><path d="M4 5h.01"/><path d="M4 12h.01"/><path d="M4 19h.01"/>',employees:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',outlets:'<path d="M3 9h18"/><path d="M5 9V5h14v4"/><path d="M5 9v11h14V9"/><path d="M9 20v-6h6v6"/>',products:'<path d="m21 8-9-5-9 5 9 5 9-5Z"/><path d="m3 8 9 5 9-5"/><path d="m3 13 9 5 9-5"/>',stocks:'<path d="M4 19V9"/><path d="M10 19V5"/><path d="M16 19v-7"/><path d="M22 19H2"/>',competitors:'<path d="M8 3H5a2 2 0 0 0-2 2v3"/><path d="M16 3h3a2 2 0 0 1 2 2v3"/><path d="M8 21H5a2 2 0 0 1-2-2v-3"/><path d="M16 21h3a2 2 0 0 0 2-2v-3"/><circle cx="12" cy="12" r="3"/>',analysis:'<path d="M3 3v18h18"/><path d="m7 15 4-4 3 3 5-7"/>',photos:'<rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="8.5" cy="10.5" r="1.5"/><path d="m21 15-5-5L5 19"/>',attendance:'<path d="M20 6 9 17l-5-5"/>',leaves:'<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M16 2v4"/><path d="M8 2v4"/><path d="M3 10h18"/>',pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/>',camera:'<path d="M14.5 4 16 7h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h3l1.5-3h5Z"/><circle cx="12" cy="13" r="3"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',plus:'<path d="M12 5v14"/><path d="M5 12h14"/>',trash:'<path d="M3 6h18"/><path d="M8 6V4h8v2"/><path d="m19 6-1 15H6L5 6"/><path d="M10 11v6"/><path d="M14 11v6"/>',download:'<path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/>',chart:'<path d="M4 19V9"/><path d="M10 19V5"/><path d="M16 19v-7"/><path d="M22 19H2"/>',briefcase:'<rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V4h8v3M3 12h18"/>'};
function icon(name,cls=''){return `<span class="phase0-icon ${cls}" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">${paths[name]||paths.chart}</svg></span>`}
const routeIcons={'#/':'home','#/tracking':'tracking','#/visits':'visits','#/employees':'employees','#/outlets':'outlets','#/products':'products','#/stocks':'stocks','#/competitors':'competitors','#/competitor-analysis':'analysis','#/field-photos':'photos','#/attendance':'attendance','#/leaves':'leaves','#/myday':'home','#/myvisits':'visits','#/mystocks':'stocks','#/myprices':'analysis','#/myintel':'competitors','#/myphotos':'photos','#/myattendance':'attendance','#/myleaves':'leaves'};
const labelIcons={'Total Karyawan':'employees','Kunjungan Hari Ini':'visits','Stok Menipis':'stocks','Ijin/Cuti Pending':'leaves','Total Foto':'photos','Lokasi':'pin','Produk':'products','Rak / Display':'stocks'};
const graphLabels=new Set(['Kunjungan Hari Ini']);
const pictographic=/\p{Extended_Pictographic}/gu;
function db(){try{return JSON.parse(localStorage.getItem('proqtrack_db_v6')||'null')}catch{return null}}
function stripEmoji(root){root.querySelectorAll('*').forEach(el=>{if(el.children.length||['SCRIPT','STYLE','SVG','PATH'].includes(el.tagName))return;const text=el.textContent||'';if(pictographic.test(text))el.textContent=text.replace(pictographic,'').replace(/\uFE0F/g,'').replace(/\s{2,}/g,' ').trim()})}
function paintLogos(root){root.querySelectorAll('.login-logo,.sidebar-logo').forEach(el=>{el.textContent='';el.setAttribute('aria-label','ProQTrack')})}
function paintNav(root){root.querySelectorAll('.nav-item').forEach(a=>{const holder=a.querySelector('.nav-icon');if(!holder||holder.dataset.vector==='1')return;holder.innerHTML=icon(routeIcons[a.getAttribute('href')]||'home');holder.dataset.vector='1'})}
function spark(seed=0){const sets=[[31,25,29,20,22,13,16],[32,30,24,27,18,21,12]];const p=sets[seed%sets.length];return `<svg class="phase0-sparkline" viewBox="0 0 96 42" preserveAspectRatio="none"><path class="area" d="M2 ${p[0]} L17 ${p[1]} L32 ${p[2]} L47 ${p[3]} L62 ${p[4]} L77 ${p[5]} L94 ${p[6]} L94 42 L2 42Z"/><path class="line" d="M2 ${p[0]} L17 ${p[1]} L32 ${p[2]} L47 ${p[3]} L62 ${p[4]} L77 ${p[5]} L94 ${p[6]}"/></svg>`}
function paintStats(root){root.querySelectorAll('.stat-card').forEach((card,i)=>{if(card.dataset.phase0==='2')return;const label=card.querySelector('.stat-label')?.textContent.trim()||'';const holder=card.querySelector('.stat-icon');if(holder)holder.innerHTML=icon(labelIcons[label]||'chart');if(graphLabels.has(label))card.insertAdjacentHTML('beforeend',spark(i));else card.classList.add('phase0-stat-clean');card.dataset.phase0='2'})}
function paintEmpty(root){root.querySelectorAll('.empty-icon').forEach(el=>{if(el.dataset.vector==='1')return;el.innerHTML=icon('search');el.dataset.vector='1'})}
function paintButtons(root){root.querySelectorAll('button').forEach(btn=>{if(btn.dataset.vector==='1'||btn.querySelector('svg'))return;const t=btn.textContent.trim().toLowerCase();const n=t.includes('hapus')?'trash':t.includes('foto')?'camera':t.includes('tambah')||t.startsWith('+')?'plus':t.includes('unduh')||t.includes('export')?'download':null;if(!n)return;btn.textContent=btn.textContent.replace(pictographic,'').replace(/^\+\s*/,'').trim();btn.insertAdjacentHTML('afterbegin',icon(n,'phase0-button-icon'));btn.dataset.vector='1'})}
function addDashboardGraph(root){const title=[...root.querySelectorAll('.card-title')].find(x=>x.textContent.includes('Progress Kunjungan'));if(!title)return;const card=title.closest('.card');if(!card||card.dataset.chart==='2')return;card.insertAdjacentHTML('beforeend','<div class="phase0-chart" aria-label="Grafik aktivitas tujuh hari"><div class="phase0-chart-bar" style="height:35%"></div><div class="phase0-chart-bar" style="height:52%"></div><div class="phase0-chart-bar" style="height:44%"></div><div class="phase0-chart-bar" style="height:68%"></div><div class="phase0-chart-bar" style="height:61%"></div><div class="phase0-chart-bar" style="height:82%"></div><div class="phase0-chart-bar" style="height:74%"></div></div><div class="phase0-chart-labels"><span>Sen</span><span>Sel</span><span>Rab</span><span>Kam</span><span>Jum</span><span>Sab</span><span>Min</span></div>');card.dataset.chart='2'}
function paintAvatars(root){const data=db();if(!data?.employees)return;const byInitial=new Map(data.employees.map(e=>[e.name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase(),e]));root.querySelectorAll('.avatar,.sidebar-avatar').forEach(el=>{if(el.querySelector('img'))return;const emp=byInitial.get(el.textContent.trim().toUpperCase());if(emp?.photo){el.innerHTML=`<img src="${emp.photo}" alt="${emp.name}">`;el.classList.add('phase0-photo-avatar')}})}
function addPortfolio(root){const title=[...root.querySelectorAll('.topbar-title')].find(x=>x.textContent.trim()==='Beranda');if(!title)return;const content=root.querySelector('.content');if(!content||content.querySelector('.phase0-portfolio'))return;const data=db();if(!data?.clients?.length||!data?.projects?.length)return;const clients=data.clients.slice(0,10);const projects=data.projects.slice(0,10);const section=document.createElement('section');section.className='phase0-portfolio';section.innerHTML=`<div class="phase0-section-head"><div><h2>Portofolio Aktif</h2><p>10 klien, 10 project, dan ${data.employees.length} tenaga lapangan</p></div><span class="phase0-live-pill">Data demo aktif</span></div><div class="phase0-client-strip">${clients.map(c=>`<div class="phase0-client-logo"><img src="${c.logo}" alt="${c.name}"></div>`).join('')}</div><div class="phase0-project-grid">${projects.slice(0,5).map(p=>{const c=clients.find(x=>x.id===p.clientId);const count=data.employees.filter(e=>e.projectId===p.id).length;return `<article class="phase0-project-card"><div class="phase0-project-icon">${icon('briefcase')}</div><div><strong>${p.name}</strong><span>${c?.name||''} · ${p.area}</span></div><b>${count} HC</b></article>`}).join('')}</div>`;content.prepend(section)}
function updateDate(root){const today=new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',day:'2-digit',month:'short',year:'numeric'}).format(new Date());root.querySelectorAll('.topbar-actions .live-badge').forEach(el=>{if(!el.textContent.includes('LIVE'))el.textContent=today})}
let queued=false;function enhance(){queued=false;const root=document;paintLogos(root);paintNav(root);paintStats(root);paintEmpty(root);paintButtons(root);paintAvatars(root);addDashboardGraph(root);addPortfolio(root);stripEmoji(root);updateDate(root)}
new MutationObserver(()=>{if(!queued){queued=true;requestAnimationFrame(enhance)}}).observe(document.documentElement,{subtree:true,childList:true});enhance();
let deferredPrompt;const install=document.createElement('button');install.className='pwa-install';install.innerHTML=`${icon('download')} Pasang ProQTrack`;document.body.appendChild(install);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;install.classList.add('show')});install.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;install.classList.remove('show')});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
