const NS='http://www.w3.org/2000/svg';
const paths={home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/>',tracking:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a8 8 0 1 0-14.8 0"/><path d="M12 22v-3"/><path d="M4.9 19.1 7 17"/><path d="m17 17 2.1 2.1"/>',visits:'<path d="M9 5h11"/><path d="M9 12h11"/><path d="M9 19h11"/><path d="M4 5h.01"/><path d="M4 12h.01"/><path d="M4 19h.01"/>',employees:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',outlets:'<path d="M3 9h18"/><path d="M5 9V5h14v4"/><path d="M5 9v11h14V9"/><path d="M9 20v-6h6v6"/>',products:'<path d="m21 8-9-5-9 5 9 5 9-5Z"/><path d="m3 8 9 5 9-5"/><path d="m3 13 9 5 9-5"/>',stocks:'<path d="M4 19V9"/><path d="M10 19V5"/><path d="M16 19v-7"/><path d="M22 19H2"/>',competitors:'<path d="M8 3H5a2 2 0 0 0-2 2v3"/><path d="M16 3h3a2 2 0 0 1 2 2v3"/><path d="M8 21H5a2 2 0 0 1-2-2v-3"/><path d="M16 21h3a2 2 0 0 0 2-2v-3"/><circle cx="12" cy="12" r="3"/>',analysis:'<path d="M3 3v18h18"/><path d="m7 15 4-4 3 3 5-7"/>',photos:'<rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="8.5" cy="10.5" r="1.5"/><path d="m21 15-5-5L5 19"/>',attendance:'<path d="M20 6 9 17l-5-5"/>',leaves:'<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M16 2v4"/><path d="M8 2v4"/><path d="M3 10h18"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/>',alert:'<path d="M10.3 2.9 1.8 17a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 2.9a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4"/><path d="M12 17h.01"/>',camera:'<path d="M14.5 4 16 7h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h3l1.5-3h5Z"/><circle cx="12" cy="13" r="3"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',plus:'<path d="M12 5v14"/><path d="M5 12h14"/>',trash:'<path d="M3 6h18"/><path d="M8 6V4h8v2"/><path d="m19 6-1 15H6L5 6"/><path d="M10 11v6"/><path d="M14 11v6"/>',download:'<path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/>',menu:'<path d="M4 6h16"/><path d="M4 12h16"/><path d="M4 18h16"/>',chart:'<path d="M4 19V9"/><path d="M10 19V5"/><path d="M16 19v-7"/><path d="M22 19H2"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',box:'<path d="m21 8-9-5-9 5 9 5 9-5Z"/><path d="M3 8v8l9 5 9-5V8"/>'};
function icon(name,cls=''){return `<span class="phase0-icon ${cls}" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">${paths[name]||paths.chart}</svg></span>`}
const routeIcons={'#/':'home','#/tracking':'tracking','#/visits':'visits','#/employees':'employees','#/outlets':'outlets','#/products':'products','#/stocks':'stocks','#/competitors':'competitors','#/competitor-analysis':'analysis','#/field-photos':'photos','#/attendance':'attendance','#/leaves':'leaves','#/myday':'home','#/myvisits':'visits','#/mystocks':'stocks','#/myprices':'analysis','#/myintel':'competitors','#/myphotos':'photos','#/myattendance':'attendance','#/myleaves':'leaves'};
const labelIcons={'Total Karyawan':'employees','Kunjungan Hari Ini':'visits','Stok Menipis':'stocks','Ijin/Cuti Pending':'leaves','Total Foto':'photos','Lokasi':'pin','Produk':'products','Rak / Display':'stocks'};
const pictographic=/\p{Extended_Pictographic}/gu;
function stripEmoji(root){root.querySelectorAll('button,.empty-state h3,.empty-state p,.card-title,.card-subtitle,.emp-area,.detail-value').forEach(el=>{if(el.childElementCount===0&&pictographic.test(el.textContent)){el.textContent=el.textContent.replace(pictographic,'').replace(/\s{2,}/g,' ').trim()}})}
function paintLogos(root){root.querySelectorAll('.login-logo').forEach(el=>{el.textContent='';el.setAttribute('aria-label','ProQTrack')});root.querySelectorAll('.sidebar-logo').forEach(el=>{el.textContent='';el.setAttribute('aria-label','ProQTrack')})}
function paintNav(root){root.querySelectorAll('.nav-item').forEach(a=>{const holder=a.querySelector('.nav-icon');if(!holder||holder.dataset.vector==='1')return;const route=a.getAttribute('href')||'';holder.innerHTML=icon(routeIcons[route]||'home');holder.dataset.vector='1'})}
function spark(seed=0){const sets=[[31,25,29,20,22,13,16],[32,30,24,27,18,21,12],[28,23,25,19,22,17,14],[34,29,31,25,20,22,17]];const p=sets[seed%sets.length];return `<svg class="phase0-sparkline" viewBox="0 0 96 42" preserveAspectRatio="none"><defs><linearGradient id="sparkFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ef5000" stop-opacity=".28"/><stop offset="1" stop-color="#ef5000" stop-opacity="0"/></linearGradient></defs><path class="area" d="M2 ${p[0]} L17 ${p[1]} L32 ${p[2]} L47 ${p[3]} L62 ${p[4]} L77 ${p[5]} L94 ${p[6]} L94 42 L2 42Z"/><path class="line" d="M2 ${p[0]} L17 ${p[1]} L32 ${p[2]} L47 ${p[3]} L62 ${p[4]} L77 ${p[5]} L94 ${p[6]}"/></svg>`}
function paintStats(root){root.querySelectorAll('.stat-card').forEach((card,i)=>{if(card.dataset.phase0==='1')return;const label=card.querySelector('.stat-label')?.textContent.trim()||'';const holder=card.querySelector('.stat-icon');if(holder){holder.innerHTML=icon(labelIcons[label]||'chart');holder.dataset.vector='1'}card.insertAdjacentHTML('beforeend',spark(i));const value=card.querySelector('.stat-value');if(value&&!card.querySelector('.phase0-delta'))value.insertAdjacentHTML('afterend','<span class="phase0-delta">↗ live</span>');card.dataset.phase0='1'})}
function paintEmpty(root){root.querySelectorAll('.empty-icon').forEach(el=>{if(el.dataset.vector==='1')return;el.innerHTML=icon('search');el.dataset.vector='1'})}
function paintButtons(root){root.querySelectorAll('button').forEach(btn=>{if(btn.dataset.vector==='1'||btn.querySelector('svg'))return;const t=btn.textContent.trim().toLowerCase();let n=t.includes('hapus')?'trash':t.includes('foto')?'camera':t.includes('tambah')||t.startsWith('+')?'plus':t.includes('unduh')||t.includes('export')?'download':null;if(!n)return;btn.textContent=btn.textContent.replace(pictographic,'').replace(/^\+\s*/,'').trim();btn.insertAdjacentHTML('afterbegin',icon(n,'phase0-button-icon'));btn.dataset.vector='1'})}
function addDashboardGraph(root){const title=[...root.querySelectorAll('.card-title')].find(x=>x.textContent.includes('Progress Kunjungan'));if(!title)return;const card=title.closest('.card');if(!card||card.dataset.chart==='1')return;const chart=document.createElement('div');chart.innerHTML='<div class="phase0-chart" aria-label="Grafik aktivitas tujuh hari"><div class="phase0-chart-bar" style="height:35%"></div><div class="phase0-chart-bar" style="height:52%"></div><div class="phase0-chart-bar" style="height:44%"></div><div class="phase0-chart-bar" style="height:68%"></div><div class="phase0-chart-bar" style="height:61%"></div><div class="phase0-chart-bar" style="height:82%"></div><div class="phase0-chart-bar" style="height:74%"></div></div><div class="phase0-chart-labels"><span>Sen</span><span>Sel</span><span>Rab</span><span>Kam</span><span>Jum</span><span>Sab</span><span>Min</span></div>';card.appendChild(chart);card.dataset.chart='1'}
function updateDate(root){const today=new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',day:'2-digit',month:'short',year:'numeric'}).format(new Date());root.querySelectorAll('.topbar-actions .live-badge').forEach(el=>{if(!el.textContent.includes('LIVE'))el.textContent=today})}
let queued=false;function enhance(){queued=false;const root=document;paintLogos(root);paintNav(root);paintStats(root);paintEmpty(root);paintButtons(root);addDashboardGraph(root);stripEmoji(root);updateDate(root)}
new MutationObserver(()=>{if(!queued){queued=true;requestAnimationFrame(enhance)}}).observe(document.documentElement,{subtree:true,childList:true});
enhance();
let deferredPrompt;const install=document.createElement('button');install.className='pwa-install';install.innerHTML=`${icon('download')} Pasang ProQTrack`;document.body.appendChild(install);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;install.classList.add('show')});install.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;install.classList.remove('show')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));